(function () {
  var n31 = function (v) { return String(v == null ? '' : v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/\s+/g, ' ').trim(); };
  var e31 = function (v) { return typeof safe === 'function' ? safe(v) : String(v == null ? '' : v); };
  var i31 = function (v) { return String(v == null ? '' : v).replace(/\D/g, ''); };
  var modal31 = function (title, body) { var d = document.createElement('div'); d.className = 'drawer'; d.innerHTML = '<aside class="drawer-card v31-preview-modal"><div class="section-head"><h2>' + title + '</h2><button class="btn secondary" id="v31-close">✕</button></div><div class="v31-preview-body">' + body + '</div><div class="form-actions"><button class="btn secondary" id="v31-close-2">Cerrar</button></div></aside>'; document.body.appendChild(d); var close = function () { d.remove(); }; d.querySelector('#v31-close').onclick = close; d.querySelector('#v31-close-2').onclick = close; };

  /* Importación: conserva el procesamiento existente y cambia únicamente la vista. */
  window.previewImport = async function (file, module, card) {
    var message = card && card.querySelector('[data-message]');
    try {
      var book = XLSX.read(await file.arrayBuffer(), { type: 'array' }), raw = XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]], { defval: '' }), rows = canonicalizeImportRows(raw, module);
      if (!rows.length) throw Error('El archivo no contiene registros.');
      var columns = Object.keys(rows[0] || {}), d = document.createElement('div'); d.className = 'drawer';
      d.innerHTML = '<aside class="drawer-card import-preview-card v31-import-modal"><div class="section-head"><h2>📥 VISTA PREVIA DE IMPORTACIÓN</h2><button class="btn secondary" id="v31-import-x">✕</button></div><div class="v31-process-info"><b>Información del proceso</b><br>Archivo: ' + e31(file.name) + '<br>Registros: ' + rows.length + '<br>Columnas: ' + columns.length + '</div><div class="v31-process-status" id="v31-import-status">✅ Archivo validado. Listo para importar.</div><h3>Todas las columnas que serán importadas</h3>' + table(rows.slice(0, 10), columns) + '<div id="v31-import-message" class="import-process"></div><div class="form-actions"><button class="btn secondary" id="v31-import-cancel">Cancelar</button><button class="btn" id="v31-import-go">📥 IMPORTAR</button></div></aside>';
      document.body.appendChild(d); var close = function () { d.remove(); }; d.querySelector('#v31-import-x').onclick = close; d.querySelector('#v31-import-cancel').onclick = close;
      d.querySelector('#v31-import-go').onclick = async function () { var button = this, out = d.querySelector('#v31-import-message'); button.disabled = true; out.textContent = '⏳ Procesando importación...'; var imported = 0, rejected = 0; for (var start = 0; start < rows.length; start += 25) { var batch = rows.slice(start, start + 25), result = await api('importRows', { module: module, rows: batch, userId: 'importacion' }); if (result.status === 'ok') imported += batch.length; else rejected += batch.length; } out.textContent = '✅ Importados: ' + imported + ' · Rechazados: ' + rejected; button.disabled = false; if (!rejected) setTimeout(function () { close(); navigate(module === 1 ? 'incidents' : module >= 2 ? 'stock' : 'inventory'); }, 700); };
    } catch (err) { if (message) message.textContent = 'Error: ' + err.message; }
  };

  function bindCards31() {
    document.querySelectorAll('#app .metric').forEach(function (card) {
      if (card.dataset.v31Bound) return; var label = n31((card.querySelector('span') || card).textContent); if (!label) return; card.dataset.v31Bound = '1'; card.classList.add('is-clickable');
      card.onclick = function () {
        var target = card.closest('.dashboard-incidents') ? 'incidents' : card.closest('.dashboard-module') ? (card.closest('.dashboard-module').classList.contains('a') ? 'modelA' : card.closest('.dashboard-module').classList.contains('b') ? 'modelB' : 'inventory') : card.closest('.dashboard-overview') ? (label.includes('STOCK') ? 'stock' : 'inventory') : '';
        if (!target) return;
        navigate(target);
        setTimeout(function () { var stateFilter = document.querySelector('#v26-d-estado') || document.querySelector('#v25-inc-estado_proceso') || document.querySelector('#v26-i-estado_proceso'), desired = label.replace(/ACTIVOS/g, 'ACTIVO').replace(/DAÑADOS/g, 'DAÑADO').replace(/PERDIDOS/g, 'PERDIDO').replace(/DEVUELTOS/g, 'DEVUELTO').replace(/PENDIENTES/g, 'PENDIENTE'); if (stateFilter && /ACTIVO|ALMACEN|DAÑADO|REPARACION|PERDIDO|BAJA|DEVUELTO|PENDIENTE/.test(desired)) { var value = Array.from(stateFilter.options).find(function (o) { return n31(o.value) === desired.replace('TOTAL ', ''); }); if (value) { stateFilter.value = value.value; stateFilter.dispatchEvent(new Event('input', { bubbles: true })); } } }, 250);
      };
    });
  }
  var baseDashboard31 = window.renderDashboard || renderDashboard;
  renderDashboard = window.renderDashboard = async function () { await baseDashboard31(); bindCards31(); };
  new MutationObserver(bindCards31).observe(document.querySelector('#app'), { childList: true, subtree: true });

  /* Buscador: conserva filtros y datos; añade acciones operativas por registro. */
  window.renderSearch = async function () {
    loading('Cargando buscador...'); try {
      var result = await Promise.all([api('listDevices'), api('listStock'), api('listIncidents')]), devices = result[0].data || [], stock = result[1].data || [], incidents = result[2].data || [];
      var rows = devices.map(function (x) { return Object.assign({}, x, { modulo: groupFor(x.modelo) === 'A' ? 'Modelos Ant. A' : groupFor(x.modelo) === 'B' ? 'Modelos Ant. B' : 'Inventario LDU', _kind: 'device', _id: x.imei }); }).concat(stock.map(function (x) { return Object.assign({}, x, { modulo: 'Stock', _kind: 'stock', _id: x.imei }); })).concat(incidents.map(function (x) { return Object.assign({}, x, { imei: x.imei || x.imei_original, responsable: x.responsable || x.nombre, modulo: 'Incidencias', _kind: 'incident', _id: x.incident_id || x.imei_original }); }));
      document.querySelector('#app').innerHTML = '<section class="section v31-search"><div class="section-head"><h2>🔎 BUSCADOR</h2><div><button class="btn secondary" id="v31-search-refresh">🔄 ACTUALIZAR</button><button class="btn secondary" id="v31-search-export">📄 EXPORTAR</button></div></div><div class="section-body"><div class="toolbar"><input id="v31-search-q" class="input search-field" placeholder="🔍 IMEI, nombre, modelo, DNI, supervisor..."><select id="v31-search-module" class="select"><option value="">TODOS LOS MÓDULOS</option><option>Inventario LDU</option><option>Modelos Ant. A</option><option>Modelos Ant. B</option><option>Stock</option><option>Incidencias</option></select></div></div><div id="v31-search-results"><div class="empty">Escribe un término para buscar.</div></div></section>';
      var draw = function () { var q = n31(document.querySelector('#v31-search-q').value), mod = document.querySelector('#v31-search-module').value, out = rows.filter(function (x) { return (!mod || x.modulo === mod) && (!q || Object.keys(x).some(function (k) { return k.charAt(0) !== '_' && n31(x[k]).includes(q); })); }); window.__searchRows = out; document.querySelector('#v31-search-results').innerHTML = q && out.length ? '<div class="table-wrap"><table><thead><tr><th>MÓDULO</th><th>IMEI</th><th>MODELO</th><th>RESPONSABLE</th><th>ESTADO</th><th>ACCIONES</th></tr></thead><tbody>' + out.map(function (x, index) { return '<tr><td>' + e31(x.modulo) + '</td><td>' + e31(x.imei) + '</td><td>' + e31(x.modelo) + '</td><td>' + e31(x.responsable) + '</td><td>' + e31(x.estado || x.estado_proceso) + '</td><td class="row-actions"><button data-v31-action="view" data-index="' + index + '">👁️</button><button data-v31-action="history" data-index="' + index + '">📋</button><button data-v31-action="edit" data-index="' + index + '">✎️</button><button data-v31-action="delete" data-index="' + index + '">🗑️</button></td></tr>'; }).join('') + '</tbody></table></div>' : '<div class="empty">' + (q ? 'Sin resultados.' : 'Escribe un término para buscar.') + '</div>'; document.querySelectorAll('[data-v31-action]').forEach(function (button) { button.onclick = async function () { var x = out[Number(button.dataset.index)]; if (!x) return; if (button.dataset.v31Action === 'view') return showDetail(x); if (button.dataset.v31Action === 'history') { state.historyImei = x.imei; return navigate('history'); } if (button.dataset.v31Action === 'edit') return x._kind === 'incident' ? openIncidentForm(x) : openDeviceForm(x); if (button.dataset.v31Action === 'delete' && confirm('¿Enviar este registro al módulo Eliminar?')) { await api('deleteDevice', { imei: x.imei, justification: 'Eliminación desde Buscador', userId: 'web-user' }); draw(); } }; }); };
      document.querySelector('#v31-search-q').oninput = draw; document.querySelector('#v31-search-module').onchange = draw; document.querySelector('#v31-search-refresh').onclick = renderSearch; document.querySelector('#v31-search-export').onclick = function () { exportRows(window.__searchRows || [], 'buscador'); }; draw();
    } catch (err) { errorView('No se pudo cargar Buscador', err, 'renderSearch'); }
  };

  /* Notificaciones: selección de IMEI, módulo de origen y vista previa completa. */
  window.renderNotifications = async function () {
    loading('Cargando notificaciones...'); try {
      var devices = renderUnifiedRows(await loadUnified()), history = (await api('listNotifications')).data || [], selected = null, previewed = false;
      document.querySelector('#app').innerHTML = '<section class="section v31-notifications"><div class="section-head"><h2>🔔 NOTIFICACIONES</h2><button class="btn secondary" onclick="renderNotifications()">🔄 ACTUALIZAR</button></div><form id="v31-notification-form" class="device-form"><h3>📱 SELECCIONAR IMEI</h3><input id="v31-imei-q" class="input" placeholder="Buscar IMEI, responsable, modelo..."><div id="v31-imei-list" class="selection-list"></div><div id="v31-imei-detail" class="v31-imei-detail empty">Selecciona un IMEI para cargar su información.</div><h3>📤 REDACTAR Y ENVIAR</h3><div class="form-grid">' + selectField('Tipo de notificación','type',['⚠️ Incidencia registrada','📦 Cambio de stock','📋 Cambio de responsable']) + field('Asunto','subject','text','Notificación LDU','required') + '<label class="full-field"><span>Destinatarios *</span><input class="input" name="recipient" placeholder="correo@dominio.com" required></label>' + field('CC','cc','text','') + '<label class="full-field"><span>Mensaje</span><textarea class="input" name="message" rows="9" required></textarea></label></div><div class="form-actions"><button type="button" class="btn secondary" id="v31-preview">👁️ VISTA PREVIA</button><button type="submit" class="btn" id="v31-send">📤 ENVIAR</button></div><div id="v31-notification-msg"></div></form></section><section class="section"><div class="section-head"><h2>📋 HISTORIAL DE NOTIFICACIONES ENVIADAS</h2></div>' + table(history, ['timestamp','type','subject','recipient','zona','role','email','cc','sender','status']) + '</section>';
      var form = document.querySelector('#v31-notification-form'), detail = document.querySelector('#v31-imei-detail'), message = form.querySelector('[name="message"]');
      var draw = function () { var q = n31(document.querySelector('#v31-imei-q').value), list = devices.filter(function (x) { return !q || Object.keys(x).some(function (k) { return n31(x[k]).includes(q); }); }).slice(0, 30); document.querySelector('#v31-imei-list').innerHTML = list.map(function (x, index) { return '<button type="button" class="v31-imei-option" data-v31-imei="' + index + '"><b>' + e31(x.imei) + '</b><span>' + e31(x.modelo || '') + ' · ' + e31(x.modulo || 'Inventario') + '</span></button>'; }).join('') || '<div class="empty">Sin coincidencias.</div>'; document.querySelectorAll('[data-v31-imei]').forEach(function (b) { b.onclick = function () { selected = list[Number(b.dataset.v31Imei)]; previewed = false; var source = selected.modulo || selected._src || 'Inventario LDU', lines = Object.keys(selected).filter(function (k) { return k.charAt(0) !== '_'; }).map(function (k) { return '<div><b>' + e31(k.replace(/_/g, ' ')) + ':</b> ' + e31(selected[k]) + '</div>'; }).join(''); detail.className = 'v31-imei-detail'; detail.innerHTML = '<strong>Origen: ' + e31(source) + '</strong><div class="v31-imei-box">' + lines + '</div>'; message.value = '[INFORMACIÓN DEL IMEI]\nOrigen: ' + source + '\n' + Object.keys(selected).filter(function (k) { return k.charAt(0) !== '_'; }).map(function (k) { return k.replace(/_/g, ' ') + ': ' + selected[k]; }).join('\n') + '\n[/INFORMACIÓN DEL IMEI]'; }; }); };
      document.querySelector('#v31-imei-q').oninput = draw; draw(); document.querySelector('#v31-preview').onclick = function () { if (!selected) return alert('Selecciona un IMEI.'); var f = new FormData(form); modal31('👁️ VISTA PREVIA DEL MENSAJE', '<div class="v31-mail-preview"><p><b>Para:</b> ' + e31(f.get('recipient')) + '</p><p><b>Asunto:</b> ' + e31(f.get('subject')) + '</p><hr><div class="v31-message-box">' + e31(f.get('message')).replace(/\n/g, '<br>') + '</div></div>'); previewed = true; };
      form.onsubmit = async function (event) { event.preventDefault(); if (!selected) return alert('Selecciona un IMEI.'); if (!previewed) return alert('Revisa la vista previa antes de enviar.'); var f = new FormData(form), recipients = String(f.get('recipient')).split(',').map(function (x) { return x.trim(); }).filter(Boolean); if (!recipients.length || recipients.length > 4) return alert('Ingresa entre 1 y 4 destinatarios.'); var r = await api('sendNotification', { notification: { type: f.get('type'), subject: f.get('subject'), recipient: recipients.join(','), cc: f.get('cc'), message: f.get('message'), imeis: [selected.imei], module: selected.modulo || 'Inventario LDU' }, userId: 'web-user' }); document.querySelector('#v31-notification-msg').textContent = r.status === 'ok' ? '✅ Notificación enviada y registrada.' : (r.message || 'No se pudo enviar.'); };
    } catch (err) { errorView('No se pudo cargar Notificaciones', err, 'renderNotifications'); }
  };

  var style31 = document.createElement('style'); style31.textContent = '.dashboard-recent .section{min-height:0}.dashboard-recent .table-wrap{max-height:145px;overflow:auto}.dashboard-recent table th,.dashboard-recent table td{padding:7px 9px;font-size:11px}.dashboard-recent .section-head{padding:8px 12px}.is-clickable{cursor:pointer;transition:transform .12s,box-shadow .12s}.is-clickable:hover{transform:translateY(-2px);box-shadow:0 8px 18px #1e3a8a22}.dashboard-module{margin-bottom:22px}.dashboard-module .module-cards{margin-bottom:20px}.v26-search-only,.v26-module-filters{margin-top:12px;margin-bottom:14px}.v26-search-only+.v26-module-filters{margin-top:0}.v31-search .section-body{padding-bottom:16px}.v31-search .table-wrap{margin-top:12px}.v31-search .row-actions button{min-width:32px}.v31-imei-option{display:flex;flex-direction:column;align-items:flex-start;width:100%;padding:9px 12px;margin:4px 0;border:1px solid #d6e1f4;border-radius:8px;background:#fff;cursor:pointer;text-align:left}.v31-imei-option:hover{background:#eef4ff;border-color:#2563eb}.v31-imei-option span{font-size:11px;color:#526788;margin-top:3px}.v31-imei-detail{margin:12px 0;padding:12px;border:1px solid #b9d0ef;border-radius:10px;background:#f7fbff}.v31-imei-box{margin-top:8px;padding:10px;border-radius:8px;background:#fff;border:1px solid #d6e1f4;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px 14px;font-size:12px}.v31-mail-preview{font-size:13px}.v31-message-box{padding:14px;border:1px solid #c8d8ef;border-radius:10px;background:#f8fbff;white-space:normal;line-height:1.45}.v31-preview-modal{width:min(720px,calc(100vw - 28px));height:auto;max-height:calc(100vh - 32px);margin:auto}.v31-preview-body{padding:18px;overflow:auto}.v31-process-info,.v31-process-status{padding:10px 12px;margin:8px 0;border:1px solid #d6e1f4;border-radius:8px;background:#eef4ff;font-size:12px}.v31-process-status{color:#087c5b;background:#ecfdf5;border-color:#b9efd9}.v31-import-modal h3{font-size:13px;margin:14px 0 8px}#v31-imei-q,#v25-history-q{min-width:420px;flex:1}@media(max-width:700px){.v31-imei-box{grid-template-columns:1fr}#v31-imei-q,#v25-history-q{min-width:100%}}'; document.head.appendChild(style31);
}());
