/* v31: ajustes finales de respuesta, usuarios, moneda y estados. */
(function(){
 'use strict';
 var oldMoney=window.money;window.money=money=function(value){var n=Number(String(value==null?'0':value).replace(/[^0-9.-]/g,''));return'S/ '+(isFinite(n)?new Intl.NumberFormat('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n):'0.00');};
 window.badge=badge=function(value){var text=String(value||'Sin estado'),k=norm(text),map={ACTIVO:'green',PERDIDO:'purple',DANADO:'red','EN REPARACION':'orange',REPARACION:'orange',BAJA:'gray',DEVUELTO:'blue','PENDIENTE DEVOLUCION':'orange',ALMACEN:'blue'};return'<span class="badge '+(map[k]||'gray')+'">'+safe(text)+'</span>';};
 var usersBase=window.renderUsers;window.renderUsers=renderUsers=async function(){await usersBase();var head=document.querySelector('.v28-users .section-head')||document.querySelector('#app .section-head');if(head&&!head.querySelector('[data-v31-refresh-users]')){var b=document.createElement('button');b.className='btn secondary';b.dataset.v31RefreshUsers='1';b.textContent='🔄 Actualizar';b.onclick=function(){renderUsers();};head.appendChild(b);}document.querySelectorAll('.v28-users tbody tr').forEach(function(row){var cell=row.cells[0];if(cell&&cell.textContent.length>4)cell.title=cell.textContent;});};
 var importBase=window.renderImport;window.renderImport=renderImport=function(){importBase();};document.addEventListener('click',function(ev){var b=ev.target.closest&&ev.target.closest('[data-v28-preview]');if(!b||b.disabled)return;b.disabled=true;b.textContent='⏳ Preparando...';setTimeout(function(){b.disabled=false;b.textContent='👁️ Revisar vista previa';},1200);},true);
 var st=document.createElement('style');st.textContent='.incidents-screen .table-wrap,.incidents-screen .module-table{margin-top:18px}.incidents-screen .toolbar,.incidents-screen .module-filters{gap:10px;margin-bottom:18px}.badge.green{background:#dcfce7;color:#166534;border-color:#86efac}.badge.purple{background:#f3e8ff;color:#6b21a8;border-color:#d8b4fe}.badge.red{background:#fee2e2;color:#991b1b;border-color:#fca5a5}.badge.orange{background:#ffedd5;color:#9a3412;border-color:#fdba74}.badge.gray{background:#e5e7eb;color:#374151;border-color:#9ca3af}.badge.blue{background:#dbeafe;color:#1e40af;border-color:#93c5fd}';document.head.appendChild(st);
}());
