/* v75: misma fuente normalizada para Dashboard, módulos y Stock. */
(function(){
  'use strict';
  function amount(value){if(value===null||value===undefined||value==='')return 0;if(typeof value==='number')return isFinite(value)?value:0;var s=String(value).replace(/[^0-9,.-]/g,'').replace(/,(?=\d{3}(?:\D|$))/g,'').replace(',','.');var n=Number(s);return isFinite(n)?n:0;}
  function status(row){return String(row&&((row.estado!==undefined&&row.estado!=='')?row.estado:row.estado_inventario)||'').trim();}
  function imei(value){return String(value==null?'':value).trim().replace(/[\u00a0\s]/g,'').replace(/\.0+$/,'').replace(/\D/g,'');}
  window.LDU_AMOUNT=amount;
  window.stockSummary=function(){var groups=[['✅ Inventario LDU','INVENTARIO'],['🟦 Modelos Antiguos A','A'],['🟧 Modelos Antiguos B','B']],stock=state.stock||[],devices=state.devices||[],by={};devices.forEach(function(d){var k=imei(d.imei);if(k)by[k]=d;});var merged=stock.map(function(r){var d=by[imei(r.imei)]||{};return Object.assign({},r,{estado:(!r.estado||norm(r.estado)==='SIN ESTADO')?d.estado||r.estado:r.estado,estado_inventario:r.estado_inventario,en_inventario:r.en_inventario});});return '<section class="section stock-summary"><div class="section-head"><h2>📦 Resumen de Stock por Modelo</h2><button class="btn secondary" onclick="renderDashboard()">🔄 Actualizar</button></div>'+groups.map(function(group){var rows=merged.filter(function(r){return groupFor(r.modelo)===group[1];}),models=[];rows.forEach(function(r){if(r.modelo&&!models.includes(r.modelo))models.push(r.modelo);});return '<div class="stock-group"><div class="stock-group-head"><h3>'+group[0]+'</h3></div>'+table(models.map(function(model){var r=rows.filter(function(x){return norm(x.modelo)===norm(model);}),t=window.totals(r);return{modelo:model,stock:r.length,en_inventario:r.filter(function(x){return norm(x.en_inventario)==='SI';}).length,activos:t.act,almacen:t.alm,danados:t.dan,en_reparacion:t.rep,perdidos:t.per,baja:t.baja,pendiente_devolucion:t.pdev,devueltos:t.dev,monto:t.valor.toFixed(2),faltante:r.filter(function(x){return norm(x.en_inventario)!=='SI';}).length};}),['modelo','stock','en_inventario','activos','almacen','danados','en_reparacion','perdidos','baja','pendiente_devolucion','devueltos','monto','faltante'])+'</div>';}).join('')+'</section>';};
  window.totals=function(rows){rows=Array.isArray(rows)?rows:[];var c=function(k){return rows.filter(function(r){return norm(status(r))===norm(k);}).length;},enInv=rows.filter(function(r){return !['DEVUELTO','BAJA'].includes(norm(status(r)));}).length;return{stock:rows===state.devices?(state.stock||[]).length:rows.length,enInv:enInv,act:c('Activo'),alm:c('Almacén'),dan:c('Dañado'),rep:c('En Reparación'),per:c('Perdido'),baja:c('Baja'),pdev:c('Pendiente Devolución'),dev:c('Devuelto'),falt:Math.max(0,rows.length-enInv),noInv:rows.filter(function(r){return r.en_inventario&&norm(r.en_inventario)==='NO';}).length,noVivo:rows.filter(function(r){return r.en_inventario&&norm(r.en_inventario)==='NO VIVO';}).length,valor:rows.reduce(function(sum,r){return sum+amount(r.monto!==undefined&&r.monto!==''?r.monto:r.valor);},0)};};
  var baseStock=window.renderStock;
  if(typeof baseStock==='function')window.renderStock=async function(){await baseStock();try{var devices=state.devices&&state.devices.length?state.devices:(await api('listDevices')).data||[],by={};devices.forEach(function(r){var k=imei(r.imei);if(k)by[k]=r;});(state.stock||[]).forEach(function(r){var d=by[imei(r.imei)],current=norm(r.estado_inventario||r.estado);if(d&&(!current||current==='SIN ESTADO'))r.estado_inventario=d.estado||'';});document.querySelectorAll('[data-stock-imei]').forEach(function(button){var row=button.closest('tr'),stock=(state.stock||[]).find(function(r){return imei(r.imei)===imei(button.dataset.stockImei);}),device=by[imei(button.dataset.stockImei)],stockState=stock&&stock.estado_inventario,value=(!stockState||norm(stockState)==='SIN ESTADO')?((device||{}).estado||'Sin estado'):stockState;if(row&&row.cells[7])row.cells[7].innerHTML=badge(value);});}catch(e){console.warn('No se pudo sincronizar estado de Stock:',e.message);}};
}());
var lduSummaryStyle=document.createElement('style');lduSummaryStyle.textContent='.stock-summary .pagination,.stock-summary .table-pager,.stock-summary [id$="-pager"]{display:none!important}';document.head.appendChild(lduSummaryStyle);

/* v76: estado del equipo e inventario son métricas diferentes. */
(function(){
  function id(v){return String(v==null?'':v).trim().replace(/[\u00a0\s]/g,'').replace(/\.0+$/,'').replace(/\D/g,'');}
  function inv(v){var k=norm(v);return k==='SI'||k==='EN INVENTARIO'||k==='YES';}
  function status(row,devices){var k=id(row&&row.imei),value=row&&((row.estado!==undefined&&row.estado!=='')?row.estado:row.estado_inventario);if(!value||norm(value)==='SIN ESTADO'){var d=(devices||[]).find(function(x){return id(x.imei)===k;});value=d&&d.estado||value;}return value||'';}
  window.totals=function(rows){rows=Array.isArray(rows)?rows:[];var devices=state.devices||[],stock=state.stock||[],byStock={};stock.forEach(function(r){var k=id(r.imei);if(k)byStock[k]=r;});var c=function(k){return rows.filter(function(r){return norm(status(r,devices))===norm(k);}).length;},scope=rows===devices?stock:stock.filter(function(s){return rows.some(function(r){return id(r.imei)===id(s.imei);});}),si=scope.filter(function(r){return inv(r.en_inventario);}).length,no=scope.filter(function(r){return norm(r.en_inventario)==='NO';}).length,nv=scope.filter(function(r){return norm(r.en_inventario)==='NO VIVO';}).length,missing=rows.filter(function(r){return !byStock[id(r.imei)];}).length;return{stock:rows===devices?stock.length:rows.length,enInv:si,act:c('Activo'),alm:c('Almacén'),dan:c('Dañado'),rep:c('En Reparación'),per:c('Perdido'),baja:c('Baja'),pdev:c('Pendiente Devolución'),dev:c('Devuelto'),falt:missing,noInv:no,noVivo:nv,valor:rows.reduce(function(sum,r){return sum+amount(r.monto!==undefined&&r.monto!==''?r.monto:r.valor);},0)};};
})();
