/* v30: módulo Eliminar estable. No depende de elementos creados por versiones anteriores. */
(function(){
 'use strict';
 var esc=function(v){return safe(v==null?'':v);};
 window.renderDelete=renderDelete=async function(){
  try{
   loading('Cargando Eliminar...');
   var rs=await Promise.all([api('listDevices'),api('listStock'),api('listIncidents'),api('listDeleted')]),rows=[],seen={};
   (rs[0].data||[]).forEach(function(x){var k=String(x.imei||'');if(k&&!seen[k]){seen[k]=1;rows.push(Object.assign({},x,{modulo:typeof groupFor==='function'?(groupFor(x.modelo)==='A'?'Modelos Ant. A':groupFor(x.modelo)==='B'?'Modelos Ant. B':'Inventario LDU'):'Inventario LDU'}));}});
   (rs[1].data||[]).forEach(function(x){var k=String(x.imei||'');if(k&&!seen[k]){seen[k]=1;rows.push(Object.assign({},x,{modulo:'Stock'}));}});
   (rs[2].data||[]).forEach(function(x){var k=String(x.imei||x.imei_original||'');if(k&&!seen[k]){seen[k]=1;rows.push(Object.assign({},x,{imei:k,modulo:'Incidencias'}));}});
   var selected=new Set(),page=1,size=20,app=document.querySelector('#app');
   app.innerHTML='<section class="section v30-delete"><div class="section-head"><h2>🗑️ Eliminar</h2><button class="btn secondary" id="v30-refresh">🔄 Actualizar</button></div><div class="cards compact v30-cards"><div class="metric"><strong>'+rows.length+'</strong><span>📊 REGISTROS</span></div><div class="metric"><strong>0</strong><span>☑️ SELECCIONADOS</span></div><div class="metric"><strong>'+new Set(rows.map(function(x){return x.modulo;}).filter(Boolean)).size+'</strong><span>📦 MÓDULOS</span></div><div class="metric"><strong>'+new Set(rows.map(function(x){return x.estado;}).filter(Boolean)).size+'</strong><span>🏷️ ESTADOS</span></div></div><div class="section-body"><input id="v30-q" class="input" placeholder="🔍 Buscar IMEI, responsable, zona..."><div class="v30-filters"><select id="v30-model" class="select"><option value="">MODELO</option></select><select id="v30-module" class="select"><option value="">MÓDULO</option><option>Inventario LDU</option><option>Modelos Ant. A</option><option>Modelos Ant. B</option><option>Stock</option><option>Incidencias</option></select><select id="v30-state" class="select"><option value="">ESTADO</option>'+LDU_STATES.map(function(x){return'<option>'+esc(x)+'</option>';}).join('')+'</select><button class="btn secondary" id="v30-all">☑️ Seleccionar página</button><input id="v30-reason" class="input" placeholder="Justificación obligatoria"><button class="btn danger" id="v30-delete">🗑️ Eliminar seleccionados</button></div></div><div id="v30-results"></div></section><section class="section"><div class="section-head"><h2>📋 Historial de eliminaciones</h2></div>'+table(rs[3].data||[],['deleted_at','deleted_by','imei','module','reason'])+'</section>';
   var model=document.querySelector('#v30-model');Array.from(new Set(rows.map(function(x){return x.modelo;}).filter(Boolean))).sort().forEach(function(x){model.insertAdjacentHTML('beforeend','<option>'+esc(x)+'</option>');});
   var draw=function(){var q=norm(document.querySelector('#v30-q').value),mo=model.value,md=document.querySelector('#v30-module').value,st=document.querySelector('#v30-state').value,out=rows.filter(function(x){return(!q||Object.values(x).some(function(v){return norm(v).indexOf(q)>=0;}))&&(!mo||x.modelo===mo)&&(!md||x.modulo===md)&&(!st||norm(x.estado)===norm(st));}),pages=Math.max(1,Math.ceil(out.length/size));page=Math.min(page,pages);var view=out.slice((page-1)*size,page*size),host=document.querySelector('#v30-results');host.innerHTML='<div class="table-wrap"><table><thead><tr><th>✓</th><th>IMEI</th><th>MARCA</th><th>MODELO</th><th>RESPONSABLE</th><th>ZONA</th><th>MÓDULO</th><th>ESTADO</th></tr></thead><tbody>'+(view.map(function(x){return'<tr><td><input type="checkbox" data-v30-imei="'+esc(x.imei)+'" '+(selected.has(String(x.imei))?'checked':'')+'></td><td>'+esc(x.imei)+'</td><td>'+esc(x.marca)+'</td><td>'+esc(x.modelo)+'</td><td>'+esc(x.responsable)+'</td><td>'+esc(x.zona)+'</td><td>'+esc(x.modulo)+'</td><td>'+badge(x.estado)+'</td></tr>';}).join('')||'<tr><td colspan="8" class="empty">Sin registros</td></tr>')+'</tbody></table></div><div class="pagination"><span>Página '+page+' de '+pages+' · '+out.length+' registros</span><button class="btn secondary" id="v30-prev" type="button">‹</button><button class="btn secondary" id="v30-next" type="button">›</button></div>';host.querySelectorAll('[data-v30-imei]').forEach(function(c){c.onchange=function(){c.checked?selected.add(c.dataset.v30Imei):selected.delete(c.dataset.v30Imei);var n=document.querySelector('.v30-cards .metric:nth-child(2) strong');if(n)n.textContent=selected.size;};});var prev=host.querySelector('#v30-prev'),next=host.querySelector('#v30-next');if(prev)prev.onclick=function(){page=Math.max(1,page-1);draw();};if(next)next.onclick=function(){page=Math.min(pages,page+1);draw();};};
   ['v30-q','v30-model','v30-module','v30-state'].forEach(function(id){var el=document.querySelector('#'+id);if(el)el.oninput=function(){page=1;draw();};});
   var refresh=document.querySelector('#v30-refresh');if(refresh)refresh.onclick=window.renderDelete;
   var all=document.querySelector('#v30-all');if(all)all.onclick=function(){document.querySelectorAll('#v30-results [data-v30-imei]').forEach(function(c){c.checked=true;selected.add(c.dataset.v30Imei);});var n=document.querySelector('.v30-cards .metric:nth-child(2) strong');if(n)n.textContent=selected.size;};
   var del=document.querySelector('#v30-delete');if(del)del.onclick=async function(){var reason=document.querySelector('#v30-reason').value.trim();if(!reason)return alert('La justificación es obligatoria.');if(!selected.size)return alert('Selecciona registros de la página actual.');if(!confirm('Se eliminarán '+selected.size+' registros. ¿Continuar?'))return;for(var imei of selected)await api('deleteDevice',{imei:imei,justification:reason,userId:'web-user'});renderDelete();};
   draw();
  }catch(e){errorView('No se pudo cargar Eliminar',e,'renderDelete');}
 };
 var st=document.createElement('style');st.textContent='.v30-cards{display:grid;grid-template-columns:repeat(4,minmax(140px,1fr));gap:10px;margin:14px 0}.v30-filters{display:grid;grid-template-columns:1fr 1fr 1fr auto 1.4fr auto;gap:10px;margin-top:18px;padding-top:18px;border-top:1px solid #dbe5f2}.v30-delete .table-wrap{margin-top:18px}@media(max-width:900px){.v30-cards{grid-template-columns:repeat(2,1fr)}.v30-filters{grid-template-columns:1fr 1fr}}';document.head.appendChild(st);
}());
