/* v19: interfaz final y funciones interactivas consolidadas. */
(function () {
  'use strict';
  const n = v => String(v == null ? '' : v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().trim();
  const esc19 = v => typeof safe === 'function' ? safe(v) : String(v == null ? '' : v);
  const num = v => Number(String(v == null ? 0 : v).replace(/[^0-9.-]/g, '')) || 0;
  const money19 = v => `S/ ${num(v).toLocaleString('es-PE', { minimumFractionDigits: 2 })}`;
  const group19 = v => typeof groupFor === 'function' ? groupFor(v) : 'INVENTARIO';
  const label19 = { modelo:'MODELO', stock:'STOCK', en_inv:'EN INV.', activos:'ACTIVOS', almacen:'ALMACÉN', danados:'DAÑADOS', rep:'REPARAC.', perdidos:'PERDIDOS', baja:'BAJA', pdev:'P.DEV', devuelto:'DEVUELTO', monto:'MONTO S/', faltante:'FALTANTE' };

  function totals19(rows) {
    const stateOf = x => n(x.estado || x.estado_inventario || '');
    const count = (...keys) => rows.filter(x => keys.some(k => stateOf(x).includes(k))).length;
    const en = rows.filter(x => n(x.en_inventario) === 'SI' || n(x.estado) === 'ACTIVO').length;
    return { stock: rows.length, en_inv: en, activos: count('ACTIVO'), almacen: count('ALMACEN'), danados: count('DAÑ', 'DAN'), rep: count('REPAR'), perdidos: count('PERD'), baja: count('BAJA'), pdev: count('P.DEV', 'PENDIENTE'), devuelto: count('DEVUEL'), monto: rows.reduce((s, x) => s + num(x.monto || x.valor), 0), faltante: en - rows.length };
  }
  function summary19() {
    const groups = [['✅ Inventario LDU', 'INVENTARIO', 'inventory'], ['🟦 Stock Mod. A', 'A', 'modelA'], ['🟧 Stock Mod. B', 'B', 'modelB']];
    return `<section class="section stock-summary"><div class="section-head"><h2>📦 Resumen de Stock por Modelo</h2><button class="btn secondary" onclick="renderDashboard()">🔄 Actualizar</button></div>${groups.map(([title, g, view]) => { const rows = (state.devices || []).filter(x => group19(x.modelo) === g); const models = [...new Set(rows.map(x => x.modelo).filter(Boolean))]; const items = models.map(modelo => ({ modelo, ...totals19(rows.filter(x => n(x.modelo) === n(modelo))) })); items.push({ modelo: 'TOTAL', ...totals19(rows) }); return `<div class="stock-group"><div class="stock-group-head"><h3>${title}</h3><button class="btn secondary" onclick="navigate('${view}')">📋 Ver módulo</button></div>${table(items, ['modelo','stock','en_inv','activos','almacen','danados','rep','perdidos','baja','pdev','devuelto','monto','faltante'])}</div>`; }).join('')}</section>`;
  }
  window.stockSummary = summary19;

  function stockActions19(x) {
    const id = esc19(x.imei);
    return `<td class="row-actions"><button title="Ver detalle" data-v19-action="view" data-id="${id}">👁️</button><button title="Historial" data-v19-action="history" data-id="${id}">📜</button><button title="Editar" data-v19-action="edit" data-id="${id}">✎️</button><button title="Eliminar" data-v19-action="delete" data-id="${id}">✕</button></td>`;
  }
  window.renderStock = async function () {
    loading('Cargando Stock...');
    try {
      const [sr, dr] = await Promise.all([api('listStock'), api('listDevices')]);
      const stock = sr.data || [], devices = dr.data || []; state.stock = stock; state.devices = devices;
      const tabs = [['VIVO','📦 Stock Vivo'], ['A','🟦 Stock Mod. A'], ['B','🟧 Stock Mod. B']];
      document.querySelector('#app').innerHTML = `<section class="section stock-screen"><div class="section-head"><h2>📦 Stock</h2><div><button class="btn secondary" id="v19-refresh">🔄 Actualizar</button><button class="btn secondary" id="v19-export">📄 Excel</button></div></div><div class="stock-tabs">${tabs.map(([k,t],i)=>`<button class="btn ${i===0?'active':''}" data-v19-tab="${k}">${t}</button>`).join('')}</div><div class="section-body"><div class="toolbar"><input id="v19-stock-q" class="input" placeholder="🔍 Buscar IMEI, cuenta, marca o modelo..."><select id="v19-stock-state" class="select"><option value="">Todos los estados</option>${(typeof LDU_STATES !== 'undefined' ? LDU_STATES : []).map(x=>`<option>${esc19(x)}</option>`).join('')}</select></div></div><div class="stock-layout"><section class="section stock-panel"><div class="table-wrap module-table"><table><thead><tr><th>CUENTA</th><th>IMEI</th><th>MARCA</th><th>MODELO</th><th>MONTO S/</th><th>FECHA DE INGRESO</th><th>EN INVENTARIO</th><th>ESTADO</th><th>OBSERVACIONES</th><th>ACC.</th></tr></thead><tbody id="v19-stock-body"></tbody></table></div></section><section class="section stock-panel"><div class="section-head"><h2>📋 Panel del Equipo</h2></div><div id="v19-stock-detail" class="empty">Selecciona el IMEI para ver toda su información.</div></section></div></section>`;
      let active = 'VIVO', current = [];
      const draw = () => { const q = n(document.querySelector('#v19-stock-q').value), st = n(document.querySelector('#v19-stock-state').value); current = stock.filter(x => { const g = group19(x.modelo), tabOk = active === 'VIVO' ? g === 'INVENTARIO' : g === active; return tabOk && (!q || Object.values(x).some(v => n(v).includes(q))) && (!st || n(x.estado || x.estado_inventario) === st); }); document.querySelector('#v19-stock-body').innerHTML = current.map(x => `<tr><td>${esc19(x.cuenta)}</td><td><button class="link-button" data-v19-imei="${esc19(x.imei)}">${esc19(x.imei)}</button></td><td>${esc19(x.marca)}</td><td>${esc19(x.modelo)}</td><td>${money19(x.monto)}</td><td>${esc19(displayImportValue(x.fecha_ingreso, 'fecha_ingreso'))}</td><td>${esc19(x.en_inventario || '—')}</td><td>${badge(x.estado_inventario || x.estado || '—')}</td><td>${esc19(x.observaciones)}</td>${stockActions19(x)}</tr>`).join('') || '<tr><td colspan="10" class="empty">Sin resultados</td></tr>'; document.querySelectorAll('[data-v19-imei]').forEach(b => b.onclick = () => { const x = stock.find(y => String(y.imei) === String(b.dataset.v19Imei)); document.querySelector('#v19-stock-detail').innerHTML = Object.entries(x || {}).map(([k,v]) => `<div class="detail-row"><b>${esc19(label19[k] || k)}</b><span>${esc19(displayImportValue(v,k))}</span></div>`).join('') || '<div class="empty">IMEI no encontrado.</div>'; }); document.querySelectorAll('[data-v19-action]').forEach(b => b.onclick = () => { const x = current.find(y => String(y.imei) === String(b.dataset.id)); const a = b.dataset.v19Action; if (a === 'view') showDetail(x); else if (a === 'history') { state.historyImei = b.dataset.id; navigate('history'); } else if (a === 'edit') openDeviceForm(devices.find(y => String(y.imei) === String(b.dataset.id)) || x); else if (a === 'delete' && confirm('¿Enviar este IMEI al módulo Eliminar?')) api('deleteDevice', { imei:b.dataset.id, justification:'Eliminación solicitada desde Stock', userId:'web-user' }).then(renderStock); }); };
      document.querySelectorAll('[data-v19-tab]').forEach(b => b.onclick = () => { active = b.dataset.v19Tab; document.querySelectorAll('[data-v19-tab]').forEach(x => x.classList.toggle('active', x === b)); draw(); }); document.querySelector('#v19-stock-q').oninput = draw; document.querySelector('#v19-stock-state').onchange = draw; document.querySelector('#v19-refresh').onclick = renderStock; document.querySelector('#v19-export').onclick = () => exportRows(current, 'stock'); draw();
    } catch (e) { errorView('No se pudo cargar Stock', e, 'renderStock'); }
  };

  window.renderSearch = async function () { loading('Cargando buscador...'); try { const [d,s,i] = await Promise.all([api('listDevices'),api('listStock'),api('listIncidents')]); const rows = [...(d.data||[]).map(x=>({...x, modulo: group19(x.modelo)==='INVENTARIO'?'Inventario LDU':`Stock Mod. ${group19(x.modelo)}`})), ...(s.data||[]).map(x=>({...x, modulo:`Stock Mod. ${group19(x.modelo)==='INVENTARIO'?'Vivo':group19(x.modelo)}`})), ...(i.data||[]).map(x=>({...x, imei:x.imei||x.imei_original, modulo:'Incidencias'}))]; document.querySelector('#app').innerHTML = `<section class="section"><div class="section-head"><h2>🔍 Buscador General</h2><button class="btn secondary" onclick="renderSearch()">🔄 Actualizar</button></div><div class="section-body"><div class="toolbar"><input id="v19-search-q" class="input" placeholder="Buscar IMEI, responsable, supervisor, modelo o DNI..."><select id="v19-search-module" class="select"><option value="">Todos los módulos</option>${[...new Set(rows.map(x=>x.modulo))].map(x=>`<option>${esc19(x)}</option>`).join('')}</select></div></div><div id="v19-search-stats"></div><div id="v19-search-results"><div class="empty">Escribe un término para buscar.</div></div></section>`; const draw=()=>{const q=n(document.querySelector('#v19-search-q').value), m=document.querySelector('#v19-search-module').value, found=rows.filter(x=>(!m||x.modulo===m)&&(!q||Object.values(x).some(v=>n(v).includes(q)))); window.__searchRows=found; document.querySelector('#v19-search-stats').innerHTML=q?`<div class="cards module-cards">${card('🔎 Resultados',found.length)}${card('📱 IMEI',new Set(found.map(x=>x.imei).filter(Boolean)).size)}${card('📦 Módulos',new Set(found.map(x=>x.modulo)).size)}</div>`:''; document.querySelector('#v19-search-results').innerHTML=q&&found.length?table(found,['modulo','imei','marca','modelo','responsable','nombre','dni','supervisor','zona','cuenta','departamento','city','tipo','estado','monto','valor','fecha_asignacion','fecha_incidente','observaciones']):q?'<div class="empty">Sin resultados.</div>':'<div class="empty">Escribe un término para buscar.</div>'; }; document.querySelector('#v19-search-q').oninput=draw; document.querySelector('#v19-search-module').onchange=draw; } catch(e){errorView('No se pudo cargar Buscador',e,'renderSearch');} };

  const importBase = window.previewImport;
  window.previewImport = async function(file, module, host) { await importBase(file, module, host); const modal = document.querySelector('.import-preview-card'); if (!modal || modal.querySelector('#v19-progress')) return; const box=document.createElement('div'); box.id='v19-progress'; box.className='import-progress'; box.innerHTML='<strong>📊 Proceso de importación</strong><div class="progress-track"><span></span></div><small>Listo para importar</small>'; const actions=modal.querySelector('.form-actions'); if(actions) actions.before(box); const btn=modal.querySelector('#confirm-import'); if(btn) btn.onclick = async () => { btn.disabled=true; const bar=box.querySelector('span'), msg=box.querySelector('small'); msg.textContent='Validando columnas...'; bar.style.width='25%'; await new Promise(r=>setTimeout(r,250)); msg.textContent='Importando registros...'; bar.style.width='65%'; await new Promise(r=>setTimeout(r,250)); try { const book=XLSX.read(await file.arrayBuffer(),{type:'array'}), raw=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{defval:''}), rows=canonicalizeImportRows(raw,module), result=await api('importRows',{module,rows,userId:'importacion'}); bar.style.width='100%'; msg.textContent=result.status==='ok'?'✅ Importación completada.':'❌ '+(result.message||'No se pudo importar'); if(result.status==='ok') setTimeout(()=>modal.closest('.drawer')?.remove(),900); } catch(e){ msg.textContent='❌ '+e.message; btn.disabled=false; } }; };

  const style=document.createElement('style'); style.textContent='.stock-summary .stock-group{margin:14px 0}.stock-summary .stock-group-head{display:flex;align-items:center;justify-content:space-between}.stock-summary th{background:#e6eefb;color:#163b79}.stock-summary td,.stock-summary th{text-align:center}.stock-summary td:first-child,.stock-summary th:first-child{text-align:left}.stock-summary tbody tr:last-child{font-weight:800;background:#edf3ff}.stock-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.stock-tabs .active{background:#2563eb;color:#fff}.row-actions{white-space:nowrap}.row-actions button{border:1px solid #d6deed;background:#fff;border-radius:8px;margin:1px;padding:5px;cursor:pointer}.row-actions button:hover{transform:translateY(-1px);box-shadow:0 2px 6px #94a3b833}.detail-row{display:flex;justify-content:space-between;gap:12px;border-bottom:1px solid #e5eaf3;padding:8px 2px}.detail-row b{color:#2d4d7c}.import-progress{margin:14px 0;padding:12px;border:1px solid #b7c9f7;border-radius:10px;background:#f5f8ff}.progress-track{height:9px;background:#dbe5fb;border-radius:9px;overflow:hidden;margin:8px 0}.progress-track span{display:block;width:0;height:100%;background:linear-gradient(90deg,#2563eb,#06b6d4);transition:width .3s}@media(max-width:700px){.stock-layout{grid-template-columns:1fr!important}.stock-summary{overflow:auto}}'; document.head.appendChild(style);
}());
