/* v24: notificaciones sin depender de wrappers antiguos. */
(function () {
  'use strict';
  var e = function (v) { return safe(v == null ? '' : v); }, k = function (v) { return String(v == null ? '' : v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase(); };
  var cols = [['fecha','📅 Fecha'],['tipo','🔔 Tipo'],['asunto','📄 Asunto'],['destinatario','👤 Destinatario'],['zona','📍 Zona'],['rol','💼 Rol'],['correo','📧 Correo'],['cc','📨 CC'],['remitente','✉️ Remitente'],['estado','✅ Estado']];
  function ficha(x) { return '<div class="table-wrap n24-ficha-wrap"><table class="n24-ficha-table"><tbody>' + Object.keys(x || {}).filter(function (n) { return n !== 'modulo'; }).map(function (n) { return '<tr><th>' + e(n.replace(/_/g, ' ')) + '</th><td>' + e(displayImportValue(x[n], n)) + '</td></tr>'; }).join('') + '</tbody></table></div>'; }
  window.renderNotifications = renderNotifications = async function () {
    loading('Cargando notificaciones...');
    try {
      var base = await loadUnified(), groups = await Promise.all([api('getGrupo', { gid: 'grpa' }), api('getGrupo', { gid: 'grpb' })]);
      groups.forEach(function (r, ix) { (r && r.data || []).forEach(function (x) { base.push({ imei:x.imei || x.IMEI, marca:x.marca || x.Marca, modelo:x.modelo || x.Modelo, responsable:x.responsable || x.Responsable, supervisor:x.supervisor || x.Supervisor, zona:x.zona || x.Zona, cuenta:x.cuenta || x.Cuenta, departamento:x.departamento || x.Region, city:x.city || x.City, estado:x.estado || x.Estado, modulo:ix ? 'Modelos Ant. B' : 'Modelos Ant. A' }); }); });
      var uniq = {}; base = base.filter(function (x) { var id = k(x.modulo) + '|' + String(x.imei || ''); if (uniq[id]) return false; uniq[id] = true; return !!x.imei; });
      var n = await api('listNotifications'), html = '<section class="section"><div class="section-head"><h2>🔔 Notificaciones</h2><button class="btn secondary" id="n24-refresh">🔄 Actualizar</button></div><div class="section-body"><div class="toolbar"><input id="n24-q" class="input search-field" placeholder="🔍 Buscar IMEI, responsable, supervisor o modelo..."><select id="n24-module" class="select"><option value="">Todos los módulos</option><option value="ANTA">ANTA</option>' + Array.from(new Set(base.map(function (x) { return x.modulo; }))).sort().map(function (x) { return '<option value="' + e(x) + '">' + e(x) + '</option>'; }).join('') + '</select><select id="n24-model" class="select"><option value="">Todos los modelos</option><option value="ANTA">ANTA</option>' + Array.from(new Set(base.map(function (x) { return x.modelo; }).filter(Boolean))).sort().map(function (x) { return '<option value="' + e(x) + '">' + e(x) + '</option>'; }).join('') + '</select></div><div id="n24-results" class="notification-results"></div><div id="n24-selected" class="notification-selected empty">Selecciona un IMEI; la ficha de Ant. B se carga desde el registro seleccionado.</div></div><div class="section-body"><form id="n24-form" class="device-form"><h3>📤 Redactar y enviar</h3><div class="form-grid"><label class="full-field"><span>Tipo de notificación</span><select class="select" name="type"><option>⚠️ Incidencia registrada</option><option>📦 Cambio de stock</option><option>📋 Cambio de responsable</option><option>✍️ Mensaje personalizado</option></select></label><label class="full-field"><span>Destinatarios (1 a 4 correos) *</span><input class="input" name="recipient" required></label><label><span>CC</span><input class="input" name="cc"></label><label><span>Asunto</span><input class="input" name="subject" required value="Notificación LDU"></label><label class="full-field"><span>Mensaje</span><textarea class="input" name="message" rows="6" required></textarea></label></div><div id="n24-msg"></div><button class="btn">📤 Enviar correo</button></form></div></section><section class="section"><div class="section-head"><h2>📋 Historial de Notificaciones Enviadas</h2></div><div class="table-wrap"><table><thead><tr>' + cols.map(function (c) { return '<th>' + c[1] + '</th>'; }).join('') + '</tr></thead><tbody>' + (n.data || []).map(function (r) { return '<tr>' + cols.map(function (c) { var aliases = { fecha:['fecha','timestamp'], tipo:['tipo','type'], asunto:['asunto','subject'], destinatario:['destinatario','recipient'], zona:['zona'], rol:['rol','role'], correo:['correo','email'], cc:['cc'], remitente:['remitente','sender'], estado:['estado','status'] }; var val = ''; (aliases[c[0]] || [c[0]]).some(function (a) { if (r[a] != null && r[a] !== '') { val = r[a]; return true; } }); return '<td>' + e(displayImportValue(val, c[0])) + '</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table></div></section>';
      document.querySelector('#app').innerHTML = html; var selected = null;
      function draw() { var q = k(document.querySelector('#n24-q').value), m = document.querySelector('#n24-module').value, md = document.querySelector('#n24-model').value, out = base.filter(function (x) { return (!q || Object.values(x).some(function (v) { return k(v).indexOf(q) >= 0; })) && (!m || (m === 'ANTA' ? k(x.modelo) === 'ANTA' : x.modulo === m)) && (!md || k(x.modelo) === k(md)); }); document.querySelector('#n24-results').innerHTML = out.slice(0, 100).map(function (x, i) { return '<button type="button" class="n33-imei" data-n24="' + i + '"><b>' + e(x.imei) + '</b><span>' + e(x.modulo) + ' · ' + e(x.modelo || x.responsable) + '</span></button>'; }).join('') || '<div class="empty">Sin coincidencias</div>'; document.querySelectorAll('[data-n24]').forEach(function (b) { b.onclick = function () { selected = out[Number(b.dataset.n24)]; document.querySelector('#n24-selected').innerHTML = '<strong>📍 ' + e(selected.modulo) + ' · IMEI ' + e(selected.imei) + '</strong><div class="n33-imei-box">' + ficha(selected) + '</div>'; document.querySelector('#n24-form [name="message"]').value = 'Detalle del equipo seleccionado:\n\n' + Object.keys(selected).map(function (x) { return x + ': ' + selected[x]; }).join('\n'); }; }); }
      draw(); document.querySelector('#n24-q').oninput = draw; document.querySelector('#n24-module').onchange = draw; document.querySelector('#n24-model').onchange = draw; document.querySelector('#n24-refresh').onclick = renderNotifications;
      document.querySelector('#n24-form').onsubmit = async function (ev) { ev.preventDefault(); var f = new FormData(ev.target), to = String(f.get('recipient') || '').split(',').map(function (x) { return x.trim(); }).filter(Boolean), msg = document.querySelector('#n24-msg'); if (to.length < 1 || to.length > 4) { msg.textContent = 'Ingresa entre 1 y 4 destinatarios.'; return; } msg.textContent = 'Enviando...'; var r = await api('sendNotification', { notification:{ type:f.get('type'), subject:f.get('subject'), recipient:to.join(','), recipients:to, cc:f.get('cc'), message:f.get('message'), imeis:selected ? [selected.imei] : [] }, userId:'web-user' }); msg.textContent = r && r.status === 'ok' ? '✅ Notificación enviada y registrada.' : (r && r.message || 'No se pudo enviar.'); };
    } catch (err) { errorView('No se pudo cargar Notificaciones', err, 'renderNotifications'); }
  };
}());
