/* v75: misma fuente normalizada para Dashboard, módulos y Stock. */
(function(){
  'use strict';
  function amount(value){if(value===null||value===undefined||value==='')return 0;if(typeof value==='number')return isFinite(value)?value:0;var s=String(value).replace(/[^0-9,.-]/g,'').replace(/,(?=\d{3}(?:\D|$))/g,'').replace(',','.');var n=Number(s);return isFinite(n)?n:0;}
  function status(row){return String(row&&((row.estado!==undefined&&row.estado!=='')?row.estado:row.estado_inventario)||'').trim();}
  function imei(value){return String(value==null?'':value).trim().replace(/[\u00a0\s]/g,'').replace(/\.0+$/,'').replace(/\D/g,'');}
  window.LDU_AMOUNT=amount;
  window.stockSummary=function(){var groups=[['✅ Inventario LDU','INVENTARIO'],['🟦 Modelos Antiguos A','A'],['🟧 Modelos Antiguos B','B']],source=state.stock||[];return '<section class="section stock-summary"><div class="section-head"><h2>📦 Resumen de Stock por Modelo</h2><button class="btn secondary" onclick="renderDashboard()">🔄 Actualizar</button></div>'+groups.map(function(group){var rows=source.filter(function(r){return groupFor(r.modelo)===group[1];}),models=[];rows.forEach(function(r){if(r.modelo&&!models.includes(r.modelo))models.push(r.modelo);});return '<div class="stock-group"><div class="stock-group-head"><h3>'+group[0]+'</h3></div>'+table(models.map(function(model){var r=rows.filter(function(x){return norm(x.modelo)===norm(model);}),t=window.totals(r);return{modelo:model,stock:r.length,en_inv:r.filter(function(x){return norm(x.en_inventario)==='SI';}).length,activos:t.activos||t.act,almacen:t.alm,danados:t.dan,rep:t.rep,perdidos:t.per,baja:t.baja,pdev:t.pdev,devuelto:t.dev,monto:t.valor.toFixed(2),faltante:r.filter(function(x){return norm(x.en_inventario)!=='SI';}).length};}),['modelo','stock','en_inv','activos','almacen','danados','rep','perdidos','baja','pdev','devuelto','monto','faltante'])+'</div>';}).join('')+'</section>';};
  window.totals=function(rows){rows=Array.isArray(rows)?rows:[];var c=function(k){return rows.filter(function(r){return norm(status(r))===norm(k);}).length;},enInv=rows.filter(function(r){return !['DEVUELTO','BAJA'].includes(norm(status(r)));}).length;return{stock:rows===state.devices?(state.stock||[]).length:rows.length,enInv:enInv,act:c('Activo'),alm:c('Almacén'),dan:c('Dañado'),rep:c('En Reparación'),per:c('Perdido'),baja:c('Baja'),pdev:c('Pendiente Devolución'),dev:c('Devuelto'),falt:Math.max(0,rows.length-enInv),noInv:rows.filter(function(r){return r.en_inventario&&norm(r.en_inventario)==='NO';}).length,noVivo:rows.filter(function(r){return r.en_inventario&&norm(r.en_inventario)==='NO VIVO';}).length,valor:rows.reduce(function(sum,r){return sum+amount(r.monto!==undefined&&r.monto!==''?r.monto:r.valor);},0)};};
  var baseStock=window.renderStock;
  if(typeof baseStock==='function')window.renderStock=async function(){await baseStock();try{var devices=state.devices&&state.devices.length?state.devices:(await api('listDevices')).data||[],by={};devices.forEach(function(r){var k=imei(r.imei);if(k)by[k]=r;});(state.stock||[]).forEach(function(r){var d=by[imei(r.imei)];if(d&&!r.estado_inventario)r.estado_inventario=d.estado||'';});document.querySelectorAll('[data-stock-imei]').forEach(function(button){var row=button.closest('tr'),stock=(state.stock||[]).find(function(r){return imei(r.imei)===imei(button.dataset.stockImei);}),device=by[imei(button.dataset.stockImei)],value=(stock&&stock.estado_inventario)||((device||{}).estado)||'Sin estado';if(row&&row.cells[7])row.cells[7].innerHTML=badge(value);});}catch(e){console.warn('No se pudo sincronizar estado de Stock:',e.message);}};
}());
