const GROUP_A=['V50','V50 LITE','V50LITE','Y19S','Y39','Y29S','Y04'];
const GROUP_B=['V40 SE','V40SE','V30 SE','V30SE','V25','V25E','Y36','Y28S','Y03','Y17S','Y18','Y53S','Y55','Y27','V21','Y16','Y17','Y35','Y22S'];
const STATES=['Activo','Almacen','En Reparacion','Danado','Perdido','Baja','Pendiente de Devolucion','Devuelto'];
const USES=['Exhibicion','Promotor','Red de Trabajo','Equipo en Mano','Custodia','Prestamo'];
const TYPES=['Fijo','Ruta','Supervisor','Training','GTM','Almacen'];
const ICON={home:'&#127968;',mobile:'&#128241;',warn:'&#9888;',box:'&#128230;',search:'&#128269;',history:'&#128220;',bell:'&#128276;',trash:'&#128465;',import:'&#128229;',clock:'&#9201;',users:'&#128101;',gear:'&#9881;',refresh:'&#128260;',add:'&#43;',export:'&#128228;',eye:'&#128065;',edit:'&#9998;',close:'&#10060;',file:'&#128196;'};
const NAV=[['PRINCIPAL',[['home','Dashboard','dashboard']]],['MODULOS',[['mobile','Inventario LDU','inventory'],['warn','Incidencias','incidents'],['box','Stock','stock'],['box','Modelos Ant. A','model-a'],['box','Modelos Ant. B','model-b']]],['HERRAMIENTAS',[['search','Buscador','search'],['history','Historial IMEI','history'],['bell','Notificaciones','notifications'],['trash','Eliminar','delete'],['import','Importar Masivo','import'],['clock','IMEIs sin Actualizar','stale'],['users','Usuarios','users'],['gear','Configuracion','settings']]]];
const DEVICE_COLS=[['imei','IMEI'],['marca','Marca'],['modelo','Modelo'],['nlinea','N. Linea'],['responsable','Responsable'],['dni','DNI'],['cargo','Cargo'],['tipo','Tipo'],['supervisor','Supervisor'],['zona','Zona'],['cuenta','Cuenta'],['departamento','Departamento'],['city','City'],['canal','Canal'],['tienda','Tienda'],['tipo_uso','Tipo Uso'],['fecha_asignacion','F. Asignacion'],['monto','Monto S/'],['estado','Estado'],['acciones','Acciones']];
const SEARCH_COLS=[['modulo','Modulo'],...DEVICE_COLS.slice(0,18),['estado','Estado'],['acciones','Acciones'],['observaciones','Observaciones'],['detalle','Detalle']];
const HISTORY_COLS=[['fecha_hora','Fecha/Hora'],['accion','Accion'],['usuario','Usuario'],...DEVICE_COLS.slice(0,18),['estado','Estado'],['observaciones','Observaciones'],['detalle','Detalle']];
const INCIDENT_COLS=[['imei_original','IMEI Original'],['tipo_incidente','Tipo Incidente'],['imei_nuevo','IMEI Nuevo'],['tipo_uso','TIPO USO DISP.'],['zona','Zona'],['supervisor','Supervisor'],['responsable','Responsable'],['dni','DNI'],['cargo','Cargo'],['marca','Marca'],['modelo','Modelo'],['fecha_incidente','Fecha incidente'],['valor','Valor'],['doc_autorizacion','Doc. Autorizacion'],['modalidad','Modalidad'],['estado_proceso','Estado proceso'],['doc_adjunto','Doc. Adjunto'],['acciones','Acciones']];
let current='dashboard';let cache={devices:[],stock:[],incidents:[]};
const $=s=>document.querySelector(s),txt=v=>String(v??'');
const val=(o,...keys)=>{for(const k of keys)if(o&&o[k]!=null)return o[k];return '';};
const esc=v=>txt(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>txt(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function date(v){if(typeof v==='number'){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return `${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`;}return txt(v);}
function group(model){const m=norm(model).toUpperCase();return GROUP_A.includes(m)?'model-a':GROUP_B.includes(m)?'model-b':'inventory';}
function row(x,mod=''){return {modulo:mod,imei:txt(val(x,'imei','IMEI','imei_original')),marca:val(x,'marca','Marca'),modelo:val(x,'modelo','Modelo'),nlinea:val(x,'nlinea','n_linea','n_linea_imei','imei_nuevo'),responsable:val(x,'responsable','nombre','nombre_completo'),dni:val(x,'dni','DNI'),cargo:val(x,'cargo','Cargo'),tipo:val(x,'tipo','Tipo'),supervisor:val(x,'supervisor','Supervisor'),zona:val(x,'zona','Zona'),cuenta:val(x,'cuenta','Cuenta'),departamento:val(x,'departamento','region','Departamento'),city:val(x,'city','City'),canal:val(x,'canal','Canal'),tienda:val(x,'tienda','Tienda'),tipo_uso:val(x,'tipo_uso','tipouso','Tipo Uso'),fecha_asignacion:date(val(x,'fecha_asignacion','fechaAsignacion','fecha_ingreso')),monto:val(x,'monto','monto_s','Monto S/'),estado:val(x,'estado','estado_inventario','Estado'),en_inventario:val(x,'en_inventario','enInventario','En Inventario'),guia:val(x,'guia','n_guia','#Guia'),observaciones:val(x,'observaciones','Observaciones'),detalle:val(x,'detalle','Detalle'),fecha_hora:val(x,'fecha_hora','timestamp','fecha'),accion:val(x,'accion','action'),usuario:val(x,'usuario','user')};}
function badge(v){return `<span class="badge status-${norm(v).replace(/\s+/g,'-')}">${esc(v||'Sin estado')}</span>`;}
function metric(label,value,icon=''){return `<div class="metric"><strong>${esc(value)}</strong><span>${icon} ${esc(label)}</span></div>`;}
function btn(label,cmd,kind='secondary'){return `<button class="btn ${kind}" data-cmd="${cmd||''}">${label}</button>`;}
function toolbar(content){return `<div class="page-toolbar">${content||''}</div>`;}
function heading(title,buttons=''){return `<div class="section-head"><h2>${title}</h2><div>${buttons}</div></div>`;}
function actions(){return `<div class="row-actions"><button data-act="view" title="Ver">${ICON.eye}</button><button data-act="history" title="Historial">${ICON.history}</button><button data-act="edit" title="Editar">${ICON.edit}</button><button data-act="delete" title="Eliminar">${ICON.close}</button></div>`;}
function table(rows,cols){return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${cols.map(c=>`<td>${c[0]==='acciones'?actions():c[0]==='estado'?badge(r[c[0]]):esc(r[c[0]]||'-')}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${cols.length}" class="empty">Sin datos</td></tr>`}</tbody></table></div>`;}
function renderNav(){const n=$('#main-nav');if(!n)return;n.innerHTML=NAV.map(([g,items])=>`<div class="nav-group">${g}</div>${items.map(([i,l,k])=>`<button class="nav-item ${current===k?'active':''}" data-nav="${k}"><span class="nav-icon">${ICON[i]}</span>${l}</button>`).join('')}`).join('');document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));}
async function load(){const [d,s,i]=await Promise.all([api('listDevices'),api('listStock'),api('listIncidents')]);cache.devices=d?.data||d?.rows||[];cache.stock=s?.data||s?.rows||[];cache.incidents=i?.data||i?.rows||[];return cache;}
async function navigate(k){current=k;renderNav();const names={dashboard:'Dashboard',inventory:'Inventario LDU',incidents:'Incidencias',stock:'Stock','model-a':'Modelos Ant. A','model-b':'Modelos Ant. B',search:'Buscador',history:'Historial IMEI',notifications:'Notificaciones',delete:'Eliminar',import:'Importar Masivo',stale:'IMEIs sin Actualizar',users:'Usuarios',settings:'Configuracion'};$('#page-title').textContent=names[k]||k;$('#app').innerHTML='<div class="loading">Cargando...</div>';try{const fn={dashboard,inventory:()=>devices('inventory','Inventario LDU'),incidents,stock,'model-a':()=>devices('model-a','Modelos Ant. A'),'model-b':()=>devices('model-b','Modelos Ant. B'),search,history,notifications,delete:remove,import:imports,stale:()=>simple('IMEIs sin Actualizar'),users,settings}[k]||dashboard;await fn();}catch(e){$('#app').innerHTML=`<section class="section"><div class="section-head"><h2>${ICON.close} No se pudo cargar ${esc(names[k])}</h2><button class="btn" data-cmd="refresh">Reintentar</button></div><div class="error">${esc(e.message)}</div></section>`;wire();}}
function states(rows){const a=rows.map(x=>row(x));return [['TOTAL',a.length],...STATES.map(s=>[s,a.filter(x=>norm(x.estado)===norm(s)).length]),['IMEI NO INVENTARIO',a.filter(x=>norm(x.en_inventario)==='no').length],['IMEI NO VIVO',a.filter(x=>norm(x.en_inventario)==='no vivo').length],['VALOR TOTAL',a.reduce((n,x)=>n+(Number(x.monto)||0),0).toFixed(2)]];}
function stateSection(title,rows){return `<section class="section">${heading(title,btn(`${ICON.export} Excel`,'export'))}<div class="cards compact">${states(rows).map(x=>metric(x[0],x[1])).join('')}</div></section>`;}
async function dashboard(){await load();const all=cache.devices.concat(cache.stock).map(x=>row(x));const count=s=>all.filter(x=>norm(x.estado)===norm(s)).length;$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh','primary')+btn(`${ICON.add} Dispositivo`,'device','primary')+btn(`${ICON.import} Importar Masivo`,'import')+btn(`${ICON.export} Exportar Excel`,'export'))+`<div class="cards dashboard-overview">${metric('TOTAL STOCK',cache.stock.length,ICON.box)}${metric('TOTAL EN INVENTARIO',cache.devices.length,ICON.file)}${metric('TOTAL ACTIVOS',count('Activo'))}${metric('TOTAL EN ALMACEN',count('Almacen'))}${metric('TOTAL DANADOS',count('Danado'))}${metric('TOTAL EN REPARACION',count('En Reparacion'))}${metric('TOTAL PERDIDOS',count('Perdido'))}${metric('TOTAL EN BAJA',count('Baja'))}${metric('PENDIENTE DE DEVOLUCION',count('Pendiente de Devolucion'))}${metric('TOTAL DEVUELTOS',count('Devuelto'))}${metric('TOTAL IMEI NO INVENTARIO',all.filter(x=>norm(x.en_inventario)==='no').length)}${metric('TOTAL IMEI NO VIVO',all.filter(x=>norm(x.en_inventario)==='no vivo').length)}${metric('VALOR TOTAL',all.reduce((n,x)=>n+(Number(x.monto)||0),0).toFixed(2))}</div>${stateSection('Estados - Inventario LDU',all.filter(x=>group(x.modelo)==='inventory'))}${stateSection('Estados - Modelos Antiguos A',all.filter(x=>group(x.modelo)==='model-a'))}${stateSection('Estados - Modelos Antiguos B',all.filter(x=>group(x.modelo)==='model-b'))}<section class="section">${heading('Incidencias',btn(`${ICON.export} Excel`,'export'))}<div class="cards compact">${metric('TOTAL',cache.incidents.length)}${metric('PENDIENTE',cache.incidents.filter(x=>norm(val(x,'estado_proceso','estado'))==='pendiente').length)}${metric('EN CURSO',cache.incidents.filter(x=>norm(val(x,'estado_proceso','estado'))==='en curso').length)}${metric('DANADOS',cache.incidents.filter(x=>norm(val(x,'tipo_incidente','tipo'))==='dano').length)}${metric('PERDIDOS',cache.incidents.filter(x=>norm(val(x,'tipo_incidente','tipo'))==='perdida').length)}${metric('ROBADOS',cache.incidents.filter(x=>norm(val(x,'tipo_incidente','tipo'))==='robo').length)}${metric('OTROS',cache.incidents.filter(x=>norm(val(x,'tipo_incidente','tipo'))==='otro').length)}${metric('VALOR TOTAL',cache.incidents.reduce((n,x)=>n+(Number(val(x,'valor','monto'))||0),0).toFixed(2))}</div></section>`;wire();}
async function devices(mod,title){if(!cache.devices.length)await load();const rows=cache.devices.map(x=>row(x,title)).filter(x=>mod==='inventory'||group(x.modelo)===mod);$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh')+btn(`${ICON.export} Excel`,'export')+btn(`${ICON.add} Nuevo`,'device','primary'))+`<section class="section module-section">${heading(title)}<div class="module-filters"><input class="input" data-filter placeholder="Buscar IMEI, modelo, responsable..."><select class="select"><option>Supervisor (Todos)</option></select><select class="select"><option>Zona (Todos)</option></select><select class="select"><option>Cuenta (Todos)</option></select><select class="select"><option>Modelo (Todos)</option></select><select class="select"><option>Tipo Uso (Todos)</option></select><select class="select"><option>Estado (Todos)</option></select></div>${table(rows,DEVICE_COLS)}</section>`;wire();filterInput();}
function filterInput(){const x=$('[data-filter]');if(x)x.oninput=()=>document.querySelectorAll('tbody tr').forEach(r=>r.style.display=norm(r.textContent).includes(norm(x.value))?'':'none');}
async function incidents(){const raw=(await api('listIncidents'))?.data||[];const rows=raw.map(x=>({...row(x,'Incidencias'),imei_original:val(x,'imei_original','imei'),tipo_incidente:val(x,'tipo_incidente','tipo'),imei_nuevo:val(x,'imei_nuevo'),fecha_incidente:date(val(x,'fecha_incidente','fecha')),valor:val(x,'valor','monto'),doc_autorizacion:val(x,'doc_autorizacion'),modalidad:val(x,'modalidad'),estado_proceso:val(x,'estado_proceso','estado'),doc_adjunto:val(x,'doc_adjunto')}));cache.incidents=rows;$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh')+btn(`${ICON.export} Excel`,'export')+btn(`${ICON.add} Nueva`,'incident','primary'))+`<section class="section">${heading('Incidencias')}${table(rows,INCIDENT_COLS)}</section>`;wire();}
async function stock(){const raw=(await api('listStock'))?.data||[];const rows=raw.map(x=>row(x,'Stock'));cache.stock=raw;$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh')+btn(`${ICON.export} Excel`,'export')+btn(`${ICON.add} Nuevo`,'device','primary'))+`<section class="section stock-screen">${heading('Stock')}<div class="stock-tabs"><button class="btn secondary">Stock Vivo</button><button class="btn secondary">Stock Mod. A</button><button class="btn secondary">Stock Mod. B</button></div><div class="module-filters"><input class="input" data-filter placeholder="Buscar IMEI, marca, modelo..."><select class="select"><option>Cuenta (Todos)</option></select><select class="select"><option>Marca (Todos)</option></select><select class="select"><option>Modelo (Todos)</option></select><select class="select"><option>En Inventario (Todos)</option></select><select class="select"><option>Estado Inventario (Todos)</option></select></div>${table(rows,[['cuenta','Cuenta'],['imei','IMEI'],['marca','Marca'],['modelo','Modelo'],['monto','Monto S/'],['fecha_asignacion','Fecha ingreso'],['en_inventario','En Inventario'],['estado','Estado Inventario'],['guia','#Guia'],['observaciones','Observaciones'],['acciones','Acciones']])}</section>`;wire();filterInput();}
async function search(){const run=async()=>{const q=$('[data-query]').value.trim();if(q.length<2){$('[data-results]').innerHTML='<div class="empty">Ingrese un termino para buscar.</div>';return;}const [d,s,i]=await Promise.all([api('listDevices',{query:q}),api('listStock',{query:q}),api('listIncidents',{query:q})]);const rows=(d?.data||[]).map(x=>row(x,'Inventario')).concat((s?.data||[]).map(x=>row(x,'Stock'))).concat((i?.data||[]).map(x=>({...row(x,'Incidencias'),imei:val(x,'imei_original','imei'),tipo:val(x,'tipo_incidente','tipo'),estado:val(x,'estado_proceso','estado'),nlinea:val(x,'imei_nuevo')})));$('[data-results]').innerHTML=`<p>${rows.length} resultado(s)</p>${table(rows,SEARCH_COLS)}`;wire();};$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh')+btn(`${ICON.export} Excel`,'export'))+`<section class="section">${heading('Buscador General')}<input class="input" data-query placeholder="IMEI, nombre, modelo, DNI, supervisor..."><div data-results class="empty">Ingrese un termino para buscar.</div></section>`;wire();$('[data-query]').oninput=run;}
async function history(){const run=async()=>{const q=$('[data-history]').value.trim();if(q.length<3)return;const out=await api('listHistory',{imei:q});const rows=(out?.data||[]).map(x=>row(x,'')).map(x=>({...x,fecha_hora:date(x.fecha_hora)}));$('[data-history-result]').innerHTML=table(rows,HISTORY_COLS);};$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh')+btn(`${ICON.export} Excel`,'export'))+`<section class="section">${heading('Historial IMEI')}<input class="input" data-history placeholder="Ingrese el IMEI completo o parcial..."><div data-history-result class="empty">Ingrese un IMEI para ver su historial.</div></section>`;wire();$('[data-history]').oninput=run;}
function form(title,incident=false){const fields=incident?[['imei_original','IMEI Original'],['tipo_incidente','Tipo Incidente'],['imei_nuevo','IMEI Nuevo'],['tipo_uso','Tipo Uso'],['zona','Zona'],['supervisor','Supervisor'],['responsable','Responsable'],['dni','DNI'],['cargo','Cargo'],['marca','Marca'],['modelo','Modelo'],['fecha_incidente','Fecha incidente'],['valor','Valor'],['doc_autorizacion','Doc. Autorizacion'],['modalidad','Modalidad'],['estado_proceso','Estado proceso'],['doc_adjunto','Documentos Adjuntos (PDF, XLSX, XLS)']]:[['imei','IMEI'],['marca','Marca'],['modelo','Modelo'],['nlinea','N. Linea'],['responsable','Responsable'],['dni','DNI'],['cargo','Cargo'],['tipo','Tipo'],['supervisor','Supervisor'],['zona','Zona'],['cuenta','Cuenta'],['departamento','Departamento'],['city','City'],['canal','Canal'],['tienda','Tienda'],['tipo_uso','Tipo Uso'],['fecha_asignacion','Fecha Asignacion'],['monto','Monto S/'],['estado','Estado']];return `<div class="modal-backdrop"><form class="modal" data-form="${incident?'incident':'device'}"><div class="section-head"><h2>${title}</h2><button type="button" data-cmd="close-modal">${ICON.close}</button></div><div class="form-grid">${fields.map(([k,l])=>k==='doc_adjunto'?`<label>${l}<input type="file" name="${k}" accept=".pdf,.xlsx,.xls"></label>`:`<label>${l}<input name="${k}" ${k.includes('fecha')?'type="date"':''}></label>`).join('')}</div>${incident?'<label>Observaciones<textarea name="observaciones"></textarea></label>':''}<div class="modal-actions"><button type="button" class="btn secondary" data-cmd="close-modal">Cancelar</button><button class="btn primary" type="submit">Guardar</button></div></form></div>`;}
function openDeviceForm(){document.body.insertAdjacentHTML('beforeend',form('Nuevo Dispositivo'));wire();}
function openIncidentForm(){document.body.insertAdjacentHTML('beforeend',form('Nueva Incidencia',true));wire();}
function simple(title){$('#app').innerHTML=toolbar(btn(`${ICON.refresh} Actualizar`,'refresh'))+`<section class="section">${heading(title)}<div class="empty">Modulo preparado para la siguiente configuracion.</div></section>`;wire();}
function notifications(){simple('Notificaciones');}
function remove(){simple('Eliminar registros');}
function users(){simple('Usuarios');}
function settings(){simple('Configuracion');}
function imports(){simple('Importar Masivo');}
function wire(){document.querySelectorAll('[data-cmd]').forEach(b=>b.onclick=()=>{const c=b.dataset.cmd;if(c==='refresh')navigate(current);else if(c==='device')openDeviceForm();else if(c==='incident')openIncidentForm();else if(c==='import')navigate('import');else if(c==='close-modal')b.closest('.modal-backdrop')?.remove();else if(c==='export')alert('Exportacion preparada.');});document.querySelectorAll('[data-act="history"]').forEach(b=>b.onclick=()=>navigate('history'));document.querySelectorAll('[data-act="view"]').forEach(b=>b.onclick=()=>alert('Detalle del IMEI'));document.querySelectorAll('[data-act="edit"]').forEach(b=>b.onclick=()=>alert('Edicion del registro'));document.querySelectorAll('[data-act="delete"]').forEach(b=>b.onclick=()=>confirm('Eliminar este registro?'));document.querySelectorAll('[data-form]').forEach(f=>f.onsubmit=e=>{e.preventDefault();alert('Formulario listo para guardar en Apps Script.');f.closest('.modal-backdrop')?.remove();});}
renderNav();navigate('dashboard');
