/* apps-script-v16-patch.gs: compatible con config.gs y servicios LDU. */
function _lduPatchRow_(r){r=r||{};return{imei:r.imei||r.IMEI||r.imei_original||'',marca:r.marca||r.Marca||'',modelo:r.modelo||r.Modelo||'',n_linea:r.n_linea||r.NLinea||'',responsable:r.responsable||r.Responsable||r.nombre||r.Nombre||'',dni:r.dni||r.DNI||'',cargo:r.cargo||r.Cargo||'',tipo:r.tipo||r.Tipo||'',supervisor:r.supervisor||r.Supervisor||'',zona:r.zona||r.Zona||'',cuenta:r.cuenta||r.Cuenta||'',departamento:r.departamento||r.Departamento||r.region||r.Region||'',city:r.city||r.City||'',canal:r.canal||r.Canal||'',tienda:r.tienda||r.Tienda||'',tipo_uso:r.tipo_uso||r.TipoUso||'',fecha_asignacion:r.fecha_asignacion||r.FechaAsignacion||r.fecha_incidente||r.Fecha||'',fecha_ingreso:r.fecha_ingreso||r.FechaIngreso||'',monto:r.monto||r.Monto||r.valor||r.Valor||'',estado:r.estado||r.Estado||'',estado_proceso:r.estado_proceso||r.EstadoProceso||'',guia:r.guia||r.Guia||r.GUIA||'',observaciones:r.observaciones||r.Observaciones||'',en_inventario:r.en_inventario||r.EnInventario||'',estado_inventario:r.estado_inventario||r.EstadoInventario||'',modulo:r.source_sheet||r.modulo||r.module||''};}
function _lduPatchData_(r){return r&&Array.isArray(r.data)?r.data:Array.isArray(r)?r:[];}
function _lduCacheVersion_(){var p=PropertiesService.getScriptProperties(),v=p.getProperty('LDU_CACHE_VERSION');if(!v){v='1';p.setProperty('LDU_CACHE_VERSION',v);}return v;}
function _lduCacheKey_(name,p){return 'LDU_V25_'+_lduCacheVersion_()+'_'+name+'_'+Utilities.base64EncodeWebSafe(JSON.stringify(p||{})).slice(0,160);}
function _lduCached_(name,p,fn){try{var c=CacheService.getScriptCache(),key=_lduCacheKey_(name,p),hit=c.get(key);if(hit)return JSON.parse(hit);var value=fn();try{c.put(key,JSON.stringify(value),15);}catch(ignore){}return value;}catch(e){return fn();}}
function clearLduReadCache_(){try{PropertiesService.getScriptProperties().setProperty('LDU_CACHE_VERSION',String(Date.now()));}catch(e){}return true;}
function _lduPatchAllDevices_(){if(typeof allDeviceRows_==='function')return allDeviceRows_();return readAll_(LDU.SHEETS.DEVICES).concat(readAll_(LDU.SHEETS.MODELS_A)).concat(readAll_(LDU.SHEETS.MODELS_B));}
function getMapaLduData(p){try{p=p||{};var d=clean_(p.departamento).toUpperCase(),c=clean_(p.city).toUpperCase(),a=clean_(p.cuenta).toUpperCase(),rows=_lduPatchAllDevices_().map(_lduPatchRow_).filter(function(r){return(!d||clean_(r.departamento).toUpperCase()===d)&&(!c||clean_(r.city).toUpperCase()===c)&&(!a||clean_(r.cuenta).toUpperCase()===a);}),dep={},cit={},acc={};rows.forEach(function(r){var x=clean_(r.departamento)||'Sin departamento',y=clean_(r.city),z=clean_(r.cuenta);dep[x]=(dep[x]||0)+1;if(y)cit[y]=(cit[y]||0)+1;if(z)acc[z]=(acc[z]||0)+1;});return ok_({total:rows.length,departamentos:dep,ciudades:cit,cuentas:acc});}catch(e){return fail_('Mapa LDU: '+(e.message||e),'MAP_ERROR');}}
function getImeiSyncData(){try{var i={},s={};_lduPatchAllDevices_().forEach(function(r){var k=normalizeImei_(r.imei);if(k)i[k]=r;});_lduPatchData_(listStock_({})).forEach(function(r){var k=normalizeImei_(r.imei);if(k)s[k]=r;});return ok_({noVivo:Object.keys(i).filter(function(k){return!s[k];}),noInventario:Object.keys(s).filter(function(k){return!i[k];}),inventario:Object.keys(i).length,stock:Object.keys(s).length});}catch(e){return fail_('Sincronización IMEI: '+(e.message||e),'SYNC_ERROR');}}
function formatLduDates_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),names=Object.keys(LDU.HEADERS),cols=['timestamp','created_at','updated_at','fecha','fecha_asignacion','fecha_ingreso','fecha_incidente'];names.forEach(function(name){var sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<1)return;var h=LDU.HEADERS[name],v=sh.getDataRange().getValues();cols.forEach(function(col){var ix=h.indexOf(col);if(ix<0||v.length<2)return;for(var i=1;i<v.length;i++){var x=v[i][ix];if(typeof x==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(x)){var d=new Date(x);if(!isNaN(d.getTime()))v[i][ix]=d;}}sh.getRange(2,ix+1,Math.max(1,v.length-1),1).setValues(v.slice(1).map(function(row){return[row[ix]];})).setNumberFormat('dd-MM-yyyy / HH:mm');});});return ok_(true,'Fechas normalizadas a dd-MM-yyyy / HH:mm.');}
function formatLduDates(){return formatLduDates_();}
function listDevices(p){p=p||{};var data=_lduCached_('DEVICES',p,function(){return _lduPatchData_(listDevices_(p)).map(_lduPatchRow_);});return ok_(data,'Inventario consultado');}
function listIncidents(p){p=p||{};var data=_lduCached_('INCIDENTS',p,function(){return _lduPatchData_(listIncidents_(p)).map(_lduPatchRow_);});return ok_(data,'Incidencias consultadas');}
function listStock(p){p=p||{};var data=_lduCached_('STOCK',p,function(){return _lduPatchData_(listStock_(p)).map(_lduPatchRow_);});return ok_(data,'Stock consultado');}
function listHistory(p){p=p||{};var q=normalizeImei_(p.imei||p.query||''),data=readAll_(LDU.SHEETS.AUDIT),devices=_lduPatchAllDevices_(),byImei={};devices.forEach(function(d){var k=normalizeImei_(d.imei);if(k)byImei[k]=d;});data=data.map(function(r){var after={};try{after=JSON.parse(r.after_json||'{}')||{};}catch(e){}var before={};try{before=JSON.parse(r.before_json||'{}')||{};}catch(e){}var d=after.imei?after:(before.imei?before:(byImei[normalizeImei_(r.imei)]||{}));return Object.assign({},r,{imei:r.imei||d.imei||'',marca:d.marca||'',modelo:d.modelo||'',n_linea:d.n_linea||'',responsable:d.responsable||'',dni:d.dni||'',cargo:d.cargo||'',tipo:d.tipo||'',supervisor:d.supervisor||'',zona:d.zona||'',cuenta:d.cuenta||'',departamento:d.departamento||'',city:d.city||'',canal:d.canal||'',tienda:d.tienda||'',tipo_uso:d.tipo_uso||'',fecha_asignacion:d.fecha_asignacion||'',monto:d.monto||'',estado:d.estado||'',observaciones:d.observaciones||''});});if(q)data=data.filter(function(r){return normalizeImei_(r.imei)===q;});return ok_(data);}
function lookupImei(p){p=p||{};var k=normalizeImei_(p.imei||''),r=typeof lookupImei_==='function'?lookupImei_(k):{device:_lduPatchAllDevices_().find(function(x){return normalizeImei_(x.imei)===k;})||null,stock:listStock_({query:k}).find(function(x){return normalizeImei_(x.imei)===k;})||null};return ok_({device:r.device?_lduPatchRow_(r.device):null,stock:r.stock?_lduPatchRow_(r.stock):null});}
function getGrupo(p){p=p||{};var id=clean_(p.gid).toLowerCase(),name=id==='grpa'||id==='a'?LDU.SHEETS.MODELS_A:LDU.SHEETS.MODELS_B;return ok_(readAll_(name).map(_lduPatchRow_));}
function listUsers(){return ok_(listUsers_());}
function clearSheet(p){p=p||{};var key=String(p.sheetKey||'').toUpperCase(),allowed={INVENTORY:LDU.SHEETS.DEVICES,MODEL_A:LDU.SHEETS.MODELS_A,MODEL_B:LDU.SHEETS.MODELS_B,STOCK:LDU.SHEETS.STOCK,INCIDENTS:LDU.SHEETS.INCIDENTS,HISTORY:LDU.SHEETS.AUDIT,NOTIFICATIONS:LDU.SHEETS.NOTIFICATIONS},name=allowed[key];if(!name)return fail_('Hoja no autorizada para limpieza.','SHEET_NOT_ALLOWED');if(String(p.confirmation||'')!=='LIMPIAR '+key)return fail_('Confirmación de limpieza inválida.','CONFIRMATION_REQUIRED');if(String(p.userId||'').toLowerCase()!=='admin')return fail_('Solo el administrador puede ejecutar limpiezas.','ADMIN_REQUIRED');var lock=LockService.getScriptLock();try{lock.waitLock(30000);var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(name);if(!sh)return fail_('La hoja configurada no existe: '+name,'SHEET_NOT_FOUND');var last=sh.getLastRow(),removed=Math.max(0,last-1);if(removed>0)sh.getRange(2,1,removed,sh.getLastColumn()).clearContent();clearLduReadCache_();return ok_({sheet:key,removed:removed},'Limpieza completada para '+name+'.');}finally{try{lock.releaseLock();}catch(e){}}}
function _lduNotificationSchema_(){
  var name=LDU.SHEETS.NOTIFICATIONS,ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(name)||ss.insertSheet(name),headers=['fecha','tipo','asunto','destinatario','zona','rol','correo','cc','remitente','estado'];
  LDU.HEADERS[name]=headers;
  if(sh.getLastRow()===0){sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);return sh;}
  var current=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);
  if(current.join('|')!==headers.join('|')){
    var old=sh.getDataRange().getValues(),oldHeaders=current;
    var migrated=[headers];
    for(var i=1;i<old.length;i++){
      var o=rowToObject_(old[i],oldHeaders),row={fecha:o.timestamp||o.fecha||'',tipo:o.type||o.tipo||'',asunto:o.subject||o.asunto||'',destinatario:o.recipient||o.destinatario||'',zona:o.zona||'',rol:o.role||o.rol||'',correo:o.email||o.correo||o.recipient||'',cc:o.cc||'',remitente:o.sender||o.created_by||o.remitente||'',estado:o.status||o.estado||''};
      migrated.push(objectToRow_(row,headers));
    }
    sh.clearContents();sh.getRange(1,1,migrated.length,headers.length).setValues(migrated);sh.setFrozenRows(1);
  }
  return sh;
}
function listNotifications(){
  _lduNotificationSchema_();
  return ok_(readAll_(LDU.SHEETS.NOTIFICATIONS).map(function(x){return Object.assign({},x,{timestamp:x.fecha,type:x.tipo,subject:x.asunto,recipient:x.destinatario,email:x.correo,sender:x.remitente,status:x.estado,role:x.rol});}));
}
function sendNotification(p){
  p=p||{};var n=p.notification||p,to=clean_(n.recipient||n.to||(n.recipients||[]).join(','));if(!to)throw new Error('Debe indicar al menos un destinatario.');
  _lduNotificationSchema_();var r={fecha:now_(),tipo:clean_(n.type||n.tipo||'General'),asunto:clean_(n.subject||n.asunto||'Notificación LDU'),destinatario:to,zona:clean_(n.zona),rol:clean_(n.rol||n.role),correo:clean_(n.email||to),cc:clean_(n.cc),remitente:clean_(n.sender||p.userId||'system'),estado:'Pendiente'};
  try{MailApp.sendEmail({to:to,cc:r.cc,subject:r.asunto,htmlBody:clean_(n.message||n.mensaje||r.asunto)});r.estado='Enviada';}catch(e){r.estado='Error: '+e.message;}
  appendObject_(LDU.SHEETS.NOTIFICATIONS,r);return ok_(Object.assign({},r,{timestamp:r.fecha,type:r.tipo,subject:r.asunto,recipient:r.destinatario,email:r.correo,sender:r.remitente,status:r.estado,role:r.rol}));
}

/* Autenticación: agrega password_hash a LDU_Usuarios si todavía no existe. */
function lduAuthHash_(p){var b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(p||''),Utilities.Charset.UTF_8);return b.map(function(x){x=x<0?x+256:x;return('0'+x.toString(16)).slice(-2);}).join('');}
function lduAuthSheet_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(LDU.SHEETS.USERS)||ss.insertSheet(LDU.SHEETS.USERS),h=LDU.HEADERS[LDU.SHEETS.USERS].slice();if(h.indexOf('password_hash')<0)h.push('password_hash');if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);else{var cur=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);h.forEach(function(x){if(cur.indexOf(x)<0)sh.getRange(1,sh.getLastColumn()+1).setValue(x);});}return sh;}
function ensureLduAdmin(){var sh=lduAuthSheet_(),v=sh.getDataRange().getValues(),h=v[0].map(String),u=h.indexOf('username'),ph=h.indexOf('password_hash'),a=h.indexOf('active'),row=-1;for(var i=1;i<v.length;i++)if(String(v[i][u]||'').toLowerCase()==='admin'){row=i+1;break;}if(row<0){var n=h.map(function(x){if(x==='user_id')return Utilities.getUuid();if(x==='username')return'admin';if(x==='role')return'Administrador';if(x==='name')return'Administrador LDU';if(x==='active')return'Sí';if(x==='password_hash')return lduAuthHash_('admin');if(x==='created_at'||x==='updated_at')return now_();return'';});sh.getRange(sh.getLastRow()+1,1,1,n.length).setValues([n]);return ok_({usuario:'admin'},'Administrador creado.');}if(ph>=0&&!v[row-1][ph])sh.getRange(row,ph+1).setValue(lduAuthHash_('admin'));if(a>=0&&!v[row-1][a])sh.getRange(row,a+1).setValue('Sí');return ok_({usuario:'admin'},'Administrador verificado.');}
function login(p){p=p||{};var sh=lduAuthSheet_(),v=sh.getDataRange().getValues(),h=v[0].map(String),u=h.indexOf('username'),ph=h.indexOf('password_hash'),ri=h.indexOf('role'),name=clean_(p.usuario||p.username).toLowerCase(),pass=lduAuthHash_(p.password||'');for(var i=1;i<v.length;i++)if(String(v[i][u]||'').toLowerCase()===name&&String(v[i][ph]||'')===pass){var t=Utilities.getUuid();PropertiesService.getScriptProperties().setProperty('LDU_SESSION_'+t,JSON.stringify({usuario:name,role:v[i][ri]||'Consulta'}));return ok_({usuario:name,role:v[i][ri]||'Consulta',token:t},'Inicio de sesión correcto.');}return fail_('Usuario o contraseña incorrectos.','AUTH_ERROR');}
function logout(p){p=p||{};if(p.token)PropertiesService.getScriptProperties().deleteProperty('LDU_SESSION_'+p.token);return ok_({loggedOut:true},'Sesión cerrada.');}
function formatLduMoney_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),names=Object.keys(LDU.HEADERS),moneyCols=['monto','valor','amount','total'];names.forEach(function(name){var sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<2)return;var h=LDU.HEADERS[name]||[];moneyCols.forEach(function(col){var ix=h.indexOf(col);if(ix>=0)sh.getRange(2,ix+1,sh.getLastRow()-1,1).setNumberFormat('S/ #,##0.00');});});return ok_(true,'Montos normalizados a S/ #,##0.00.');}

/* v40: normalización de IDs, fechas y auditoría por IMEI. */
function _lduEnsureAuditSheet_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),name=LDU.SHEETS.AUDIT||'LDU_Historial_IMEI',sh=ss.getSheetByName(name)||ss.insertSheet(name),headers=['timestamp','action','user_id','imei','modulo','marca','modelo','n_linea','responsable','dni','cargo','tipo','supervisor','zona','cuenta','departamento','city','canal','tienda','tipo_uso','fecha_asignacion','monto','estado','imei_original','imei_nuevo','nombre_completo','fecha_incidente','valor','doc_autorizacion','modalidad','estado_proceso','documentos_adjuntos','before_json','after_json'];if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);else{var current=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String);headers.forEach(function(h){if(current.indexOf(h)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(h);current.push(h);}});}return sh;}
function _lduAuditImeiChange_(action,before,after,userId){try{var sh=_lduEnsureAuditSheet_(),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),row=h.map(function(key){if(key==='timestamp')return new Date();if(key==='action')return action;if(key==='user_id')return userId||'sistema';if(key==='before_json')return JSON.stringify(before||{});if(key==='after_json')return JSON.stringify(after||{});if(key==='modulo')return (after&&after.modulo)||(before&&before.modulo)||'';if(key==='imei')return (after&&after.imei)||(before&&before.imei)||(after&&after.imei_original)||(before&&before.imei_original)||'';return (after&&after[key])!=null?after[key]:(before&&before[key])!=null?before[key]:'';});sh.getRange(sh.getLastRow()+1,1,1,row.length).setValues([row]);}catch(e){Logger.log('No se pudo registrar auditoría IMEI: '+e.message);}}
function _lduNormalizeStockIds_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),name=LDU.SHEETS.STOCK,sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<2)return;var h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),ix=h.indexOf('stock_id');if(ix<0)return;var values=sh.getRange(2,ix+1,sh.getLastRow()-1,1).getValues();values.forEach(function(row,i){row[0]=String(1000+i).slice(-4);});sh.getRange(2,ix+1,values.length,1).setNumberFormat('@').setValues(values);}
function formatLduDates_(){var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),names=Object.keys(LDU.HEADERS),cols=['timestamp','created_at','updated_at','fecha','fecha_asignacion','fecha_ingreso','fecha_incidente'];names.forEach(function(name){var sh=ss.getSheetByName(name);if(!sh||sh.getLastRow()<2)return;var h=LDU.HEADERS[name]||sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(String),all=sh.getDataRange().getValues();cols.forEach(function(col){var ix=h.indexOf(col);if(ix<0)return;var out=all.slice(1).map(function(row){var value=row[ix];if(value instanceof Date)return[value];var parsed=new Date(String(value||''));return[!isNaN(parsed.getTime())?parsed:value||''];});sh.getRange(2,ix+1,out.length,1).setValues(out).setNumberFormat('dd-MM-yyyy / HH:mm');});});return ok_(true,'Fechas normalizadas a dd-MM-yyyy / HH:mm.');}
/* v49: limpieza segura y específica de Stock Mod. A/B. */
function clearSheet(p){p=p||{};var key=String(p.sheetKey||'').toUpperCase();if(key!=='STOCK_A'&&key!=='STOCK_B')return clearSheetBase_(p);if(String(p.confirmation||'')!=='LIMPIAR '+key)return fail_('Confirmación de limpieza inválida.','CONFIRMATION_REQUIRED');if(String(p.userId||'').toLowerCase()!=='admin')return fail_('Solo el administrador puede ejecutar limpiezas.','ADMIN_REQUIRED');var lock=LockService.getScriptLock();try{lock.waitLock(30000);var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(LDU.SHEETS.STOCK),modelSheet=ss.getSheetByName(key==='STOCK_A'?LDU.SHEETS.MODELS_A:LDU.SHEETS.MODELS_B);if(!sh)return fail_('La hoja configurada no existe: '+LDU.SHEETS.STOCK,'SHEET_NOT_FOUND');var modelSet={};if(modelSheet)readAll_(modelSheet).forEach(function(r){var m=clean_(r.modelo||r.Modelo).toUpperCase();if(m)modelSet[m]=true;});var values=sh.getDataRange().getValues(),headers=(values[0]||[]).map(String),modelIndex=headers.findIndex(function(h){return clean_(h).toUpperCase()==='MODELO';});if(modelIndex<0)return fail_('No se encontró la columna MODELO en Stock.','COLUMN_NOT_FOUND');var removed=0;for(var i=values.length-1;i>=1;i--){if(modelSet[clean_(values[i][modelIndex]).toUpperCase()]){sh.getRange(i+1,1,1,sh.getLastColumn()).clearContent();removed++;}}clearLduReadCache_();return ok_({sheet:key,removed:removed},'Limpieza completada para '+(key==='STOCK_A'?'Stock Mod. A':'Stock Mod. B')+'.');}finally{try{lock.releaseLock();}catch(e){}}}
function clearSheetBase_(p){p=p||{};var key=String(p.sheetKey||'').toUpperCase(),allowed={INVENTORY:LDU.SHEETS.DEVICES,MODEL_A:LDU.SHEETS.MODELS_A,MODEL_B:LDU.SHEETS.MODELS_B,STOCK:LDU.SHEETS.STOCK,INCIDENTS:LDU.SHEETS.INCIDENTS,HISTORY:LDU.SHEETS.AUDIT,NOTIFICATIONS:LDU.SHEETS.NOTIFICATIONS},name=allowed[key];if(!name)return fail_('Hoja no autorizada para limpieza.','SHEET_NOT_ALLOWED');if(String(p.confirmation||'')!=='LIMPIAR '+key)return fail_('Confirmación de limpieza inválida.','CONFIRMATION_REQUIRED');if(String(p.userId||'').toLowerCase()!=='admin')return fail_('Solo el administrador puede ejecutar limpiezas.','ADMIN_REQUIRED');var lock=LockService.getScriptLock();try{lock.waitLock(30000);var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(name);if(!sh)return fail_('La hoja configurada no existe: '+name,'SHEET_NOT_FOUND');var last=sh.getLastRow(),removed=Math.max(0,last-1);if(removed>0)sh.getRange(2,1,removed,sh.getLastColumn()).clearContent();clearLduReadCache_();return ok_({sheet:key,removed:removed},'Limpieza completada para '+name+'.');}finally{try{lock.releaseLock();}catch(e){}}}
/* v49: limpieza segura y específica de Stock Mod. A/B. */
function clearSheet(p){p=p||{};var key=String(p.sheetKey||'').toUpperCase();if(key!=='STOCK_A'&&key!=='STOCK_B')return clearSheetBase_(p);if(String(p.confirmation||'')!=='LIMPIAR '+key)return fail_('Confirmación de limpieza inválida.','CONFIRMATION_REQUIRED');if(String(p.userId||'').toLowerCase()!=='admin')return fail_('Solo el administrador puede ejecutar limpiezas.','ADMIN_REQUIRED');var lock=LockService.getScriptLock();try{lock.waitLock(30000);var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(LDU.SHEETS.STOCK),modelSheet=ss.getSheetByName(key==='STOCK_A'?LDU.SHEETS.MODELS_A:LDU.SHEETS.MODELS_B);if(!sh)return fail_('La hoja configurada no existe: '+LDU.SHEETS.STOCK,'SHEET_NOT_FOUND');var modelSet={};if(modelSheet)readAll_(modelSheet).forEach(function(r){var m=clean_(r.modelo||r.Modelo).toUpperCase();if(m)modelSet[m]=true;});var values=sh.getDataRange().getValues(),headers=(values[0]||[]).map(String),modelIndex=headers.findIndex(function(h){return clean_(h).toUpperCase()==='MODELO';});if(modelIndex<0)return fail_('No se encontró la columna MODELO en Stock.','COLUMN_NOT_FOUND');var removed=0;for(var i=values.length-1;i>=1;i--){if(modelSet[clean_(values[i][modelIndex]).toUpperCase()]){sh.getRange(i+1,1,1,sh.getLastColumn()).clearContent();removed++;}}clearLduReadCache_();return ok_({sheet:key,removed:removed},'Limpieza completada para '+(key==='STOCK_A'?'Stock Mod. A':'Stock Mod. B')+'.');}finally{try{lock.releaseLock();}catch(e){}}}
function clearSheetBase_(p){p=p||{};var key=String(p.sheetKey||'').toUpperCase(),allowed={INVENTORY:LDU.SHEETS.DEVICES,MODEL_A:LDU.SHEETS.MODELS_A,MODEL_B:LDU.SHEETS.MODELS_B,STOCK:LDU.SHEETS.STOCK,INCIDENTS:LDU.SHEETS.INCIDENTS,HISTORY:LDU.SHEETS.AUDIT,NOTIFICATIONS:LDU.SHEETS.NOTIFICATIONS},name=allowed[key];if(!name)return fail_('Hoja no autorizada para limpieza.','SHEET_NOT_ALLOWED');if(String(p.confirmation||'')!=='LIMPIAR '+key)return fail_('Confirmación de limpieza inválida.','CONFIRMATION_REQUIRED');if(String(p.userId||'').toLowerCase()!=='admin')return fail_('Solo el administrador puede ejecutar limpiezas.','ADMIN_REQUIRED');var lock=LockService.getScriptLock();try{lock.waitLock(30000);var ss=SpreadsheetApp.openById(LDU.SPREADSHEET_ID),sh=ss.getSheetByName(name);if(!sh)return fail_('La hoja configurada no existe: '+name,'SHEET_NOT_FOUND');var last=sh.getLastRow(),removed=Math.max(0,last-1);if(removed>0)sh.getRange(2,1,removed,sh.getLastColumn()).clearContent();clearLduReadCache_();return ok_({sheet:key,removed:removed},'Limpieza completada para '+name+'.');}finally{try{lock.releaseLock();}catch(e){}}}
